import type { Proposal } from '../lib/coaching'
import { fmtDayYear } from '../lib/format'
import { formatPrescriptionValue } from '../lib/coach-format'
const labels:Record<string,string>={monitoring:'Monitoring, insufficient independent pace evidence',improvement_supported:'Improvement supported',reduction_supported:'Reduction supported',on_track:'On track',mixed_evidence:'Mixed evidence',excluded:'No eligible pace evidence'}
export function ProposalEvidence({proposal}:{proposal:Proposal}) {
 const assessment=proposal.evidenceSummary,metrics=proposal.metrics,coverage=proposal.coverage
 if(!assessment&&!metrics&&!coverage)return <p className="coach-muted">Training assessment and recorded coverage were not supplied with this preview.</p>
 return <section aria-label="Training evidence"><h3>Training evidence</h3><p>Recorded training and planned prescriptions are separate. Missing records do not prove rest or complete history.</p>{assessment&&<><p><strong>Pace assessment:</strong> {labels[assessment.paceStatus || ''] || 'Unknown'}{assessment.paceDirection?` · Direction ${assessment.paceDirection}`:''}</p><p>{assessment.independentEligibleDays ?? 'Unknown'} independent eligible days · Minimum {assessment.minimumIndependentDays ?? 'unknown'}.</p>{assessment.paceReason&&<p>{assessment.paceReason}</p>}<p>Explicit missed sessions: {assessment.explicitMissCount ?? 'unknown'} · Elapsed gap: {assessment.elapsedGapDays == null?'unknown':`${assessment.elapsedGapDays} days`} · Gap coverage: {assessment.gapCoverage || 'unknown'}.</p><p>Interruption review: {assessment.interruptionReview == null?'unknown':assessment.interruptionReview?'required':'not triggered'}.</p>{assessment.interruptionPolicy&&<p>{assessment.interruptionPolicy}</p>}<p>Partial week treatment: {assessment.partialWeekTreatment || 'unknown'}.</p></>}
 <p>History: {coverage?.history?.replaceAll('_',' ') || 'unknown'} · Ingestion completeness: {coverage?.ingestionCompleteness || 'unknown'}.</p>
 {metrics&&<><p>Recorded totals: {metrics.session_count ?? 'unknown'} sessions · {metrics.actual_distance_meters == null?'Distance unknown':formatPrescriptionValue('distance_meters',metrics.actual_distance_meters)} · {metrics.actual_duration_seconds == null?'Duration unknown':formatPrescriptionValue('duration_seconds',metrics.actual_duration_seconds)}. Timezone: {metrics.timezone || 'unknown'}.</p><p>{metrics.planned_future_session_count ?? 'Unknown'} planned future sessions, separate from recorded totals.</p>{Object.entries(metrics.weeks || {}).map(([week,row])=><details className="coach-session coach-evidence-week" key={week}><summary>Week beginning {fmtDayYear(week)} · {row.partial_week?'Partial week':'Recorded week'}</summary><div className="coach-session-body"><p>Recorded: {row.session_count} sessions · {formatPrescriptionValue('distance_meters',row.distance_meters)} · {formatPrescriptionValue('duration_seconds',row.duration_seconds)}.</p><p>Unknown distance: {row.unknown_distance_sessions} sessions · Unknown duration: {row.unknown_duration_sessions} sessions.</p><p>Longest recorded run: {formatPrescriptionValue('distance_meters',row.longest_run_meters)} · Share {row.longest_run_share==null?'unknown':`${Math.round(row.longest_run_share*100)}%`}.</p><p>Hard sessions: {row.hard_session_count} · Evidence: {row.hard_session_evidence?.replaceAll('_',' ') || 'unknown'}.</p><p>Planned: {row.planned_session_count} sessions · {formatPrescriptionValue('distance_meters',row.planned_distance_meters)} · {formatPrescriptionValue('duration_seconds',row.planned_duration_seconds)}{row.planned_estimated?' · Estimated':''}.</p><p>Actual / planned distance: {row.actual_vs_planned_distance_ratio==null?'Not compared':`${Math.round(row.actual_vs_planned_distance_ratio*100)}%`} · {row.comparison_status?.replaceAll('_',' ') || 'unknown'}.</p></div></details>)}</>}
 </section>
}
