import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {useFixtureSession,fixtureApi} from './helpers'
test('WEB-ADMIN-CREATE002 member admin roles empty long labels and held creation persist once with busy cancellation locked',async({page,request},info)=>{
 for(const [id,states]of Object.entries({'web.users.create-display-name':['empty','long'],'web.users.create-role':['member','admin'],'web.users.create-save':['inflight']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('admin'),created:string[]=[];const users=async()=>{const response=await request.get('/api/admin/users',auth);expect(response.status()).toBe(200);return await response.json()};await useFixtureSession(page,'admin');await page.goto('/users')
 try{for(const role of ['user','admin']){const username=`qa-role-${randomUUID().slice(0,8)}`,display=role==='admin'?'Synthetic long label '+ 'é'.repeat(80):'',password=`qa-secret-${randomUUID()}`;let release!:()=>void,entered!:()=>void,posts=0;const gate=new Promise<void>(resolve=>release=resolve),held=new Promise<void>(resolve=>entered=resolve);await page.route('**/api/admin/users',async route=>{if(route.request().method()!=='POST')return route.continue();posts++;entered();await gate;const response=await route.fetch();expect(response.status()).toBe(201);const user=await response.json();created.push(user.id);await route.fulfill({response})})
 try{await page.getByRole('button',{name:'Create user',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Create member',exact:true});await dialog.getByLabel('Username',{exact:true}).fill(username);await dialog.getByLabel('Display name',{exact:true}).fill(display);await dialog.getByLabel('Password',{exact:true}).fill(password);const roleButton=dialog.getByRole('button',{name:role==='admin'?'Admin':'Member',exact:true});await roleButton.focus();await page.keyboard.press('Enter');await expect(roleButton).toHaveClass(/on/);await dialog.getByRole('button',{name:'Create member',exact:true}).click();await held;await expect(dialog.getByRole('button',{name:'Creating…',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();expect((await users()).some((user:{username:string})=>user.username===username)).toBe(false);release();await expect(dialog).toHaveCount(0);expect(posts).toBe(1);const saved=(await users()).filter((user:{username:string})=>user.username===username);expect(saved).toHaveLength(1);expect(saved[0]).toMatchObject({role,displayName:display||username,isActive:true});await page.reload();const row=page.locator('.u-row').filter({hasText:username});await expect(row).toContainText(display||username)
 }finally{release();await page.unroute('**/api/admin/users')}}
 }finally{for(const id of created){const retired=await request.patch(`/api/admin/users/${id}`,{...auth,data:{isActive:false}});expect(retired.status()).toBe(200)}}
})
