import {fillElapsed} from './elapsed-helpers'
import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {sessionFile,useFixtureSession,fixtureApi,accounts} from './helpers'
for(const suppressStorageEvent of [false,true])test(`WEB-AUTH-CROSS001 another tab changing account prevents old facts with new credential; storage event suppressed ${suppressStorageEvent}`,async({page,context,request},info)=>{
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.coach.profile-save',states:suppressStorageEvent?['cross_tab_account_change','credential_race_blocked']:['cross_tab_account_change']})})
 if(suppressStorageEvent)await page.addInitScript(()=>window.addEventListener('storage',event=>event.stopImmediatePropagation(),true))
 const sessions=JSON.parse(readFileSync(sessionFile,'utf8'));await useFixtureSession(page,'athlete');await page.goto('/coach');await expect(page.getByLabel('Benchmark source',{exact:true})).toBeEnabled();const originalFacts=await page.getByLabel('Benchmark source',{exact:true}).inputValue();expect(originalFacts).not.toBe('');await page.getByLabel('Goal',{exact:true}).selectOption('general_fitness');await page.getByLabel('Event date',{exact:true}).fill('');await fillElapsed(page,'Target time (optional)','');await fillElapsed(page,'Current pace','6:00',true);await page.getByLabel('Current weekly distance (km)',{exact:true}).fill('18');await page.getByLabel('Current longest run (km)',{exact:true}).fill('6');await page.getByLabel('Benchmark observation time (local)',{exact:true}).fill('2026-10-09T10:00');await page.getByLabel('Benchmark confidence (optional, 0–1)',{exact:true}).fill('');for(const chip of await page.getByRole('group',{name:'Available training days',exact:true}).getByRole('button').all()){if(await chip.getAttribute('aria-pressed')==='true')await chip.click()}await page.getByRole('button',{name:'mon',exact:true}).click()
 const me=await request.get('/api/auth/me',fixtureApi('athleteB'));expect(me.status()).toBe(200);expect((await me.json()).user.id).toBe(sessions.athleteB.user.id)
 let mixedWrites=0;await page.route('**/api/coaching/profile',route=>{if(route.request().method()==='PUT'){if(route.request().headers().authorization===`Bearer ${sessions.athleteB.token}`&&route.request().postDataJSON().benchmark?.source===originalFacts)mixedWrites++;return route.abort('failed')}return route.continue()})
 const other=await context.newPage();await other.goto('/login');await other.evaluate(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},sessions.athleteB)
 // Let the storage event either adopt the new account or fail closed before the old form may submit.
 await page.waitForTimeout(250);const save=page.getByRole('button',{name:'Save coaching profile',exact:true});if(await save.isVisible()&&await save.isEnabled()){await save.click();await expect(page.getByLabel('Username',{exact:true})).toBeVisible();}
 expect(mixedWrites,'No old-account profile data may be sent using a credential selected in another tab').toBe(0);await expect(page.getByLabel('Username',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Save coaching profile',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('loopback.user')||'null')?.id)).toBe(sessions.athleteB.user.id);await page.addInitScript(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},sessions.athleteB);await page.goto('/settings');await expect(page.locator('.page-title')).toHaveText('Settings');await expect(page.locator('.u-name')).toHaveText(sessions.athleteB.user.displayName||sessions.athleteB.user.username);await page.reload();await expect(page.locator('.page-title')).toHaveText('Settings');await other.close()
})

test('WEB-AUTH-CROSS002 actual expired scoped session clears principal and allows clean repeated login recovery',async({page,request},info)=>{
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.login.submit',states:['expired_session_recovery','repeated_disabled_recovery']})},{type:'control',description:JSON.stringify({id:'web.layout.logout',states:['expired_recovered_session_revoked']})})
 test.setTimeout(45_000);const sessions=JSON.parse(readFileSync(sessionFile,'utf8')),expires=Date.now()+10_000;const minted=await request.post('/api/auth/tokens',{...fixtureApi('athleteB'),data:{name:'Synthetic expiry QA',expiresAt:new Date(expires).toISOString()}});expect(minted.status()).toBe(201);const token=await minted.json();const session={token:token.token,tokenId:token.tokenId,user:sessions.athleteB.user}
 try{await page.addInitScript(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},session);await page.goto('/coach');await expect(page.getByRole('button',{name:'Refresh status',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Request review',exact:true})).toBeEnabled();const unauthorized=page.waitForResponse(response=>response.url().includes('/api/coaching/status')&&response.status()===401,{timeout:20000});await page.waitForTimeout(Math.max(0,expires-Date.now()+100));const refresh=page.getByRole('button',{name:'Refresh status',exact:true});if(await refresh.isVisible())await refresh.click();await unauthorized;await expect(page.getByLabel('Username',{exact:true})).toBeVisible();expect(await page.evaluate(()=>[localStorage.getItem('loopback.token'),localStorage.getItem('loopback.user'),localStorage.getItem('loopback.tokenId')])).toEqual([null,null,null]);await expect(page.getByRole('button',{name:'Save coaching profile',exact:true})).toHaveCount(0)
 let logins=0;let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/api/auth/login',async route=>{logins++;await gate;await route.continue()});await page.getByLabel('Username',{exact:true}).fill(accounts.athleteB.username);await page.getByLabel('Password',{exact:true}).fill(accounts.athleteB.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();try{await expect(page.getByRole('button',{name:'Signing in…',exact:true})).toBeDisabled();await page.keyboard.press('Enter');expect(logins).toBe(1)}finally{release()}await expect(page.locator('.page-title')).toHaveText('Hey Synthetic');const recovered=await page.evaluate(()=>({token:localStorage.getItem('loopback.token'),tokenId:localStorage.getItem('loopback.tokenId'),user:JSON.parse(localStorage.getItem('loopback.user')||'null')}));expect(recovered.user.id).toBe(sessions.athleteB.user.id);const me=await request.get('/api/auth/me',{headers:{Authorization:`Bearer ${recovered.token}`}});expect(me.status()).toBe(200);expect((await me.json()).user.id).toBe(sessions.athleteB.user.id);if(await page.getByRole('button',{name:'Menu',exact:true}).isVisible())await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByTitle('Log out',{exact:true}).click();await expect(page.getByLabel('Username',{exact:true})).toBeVisible();expect((await request.get('/api/auth/me',{headers:{Authorization:`Bearer ${recovered.token}`}})).status()).toBe(401)
 }finally{const removed=await request.delete(`/api/auth/tokens/${session.tokenId}`,fixtureApi('athleteB'));expect([204,404]).toContain(removed.status())}
})
