import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {accounts,fixtureApi,sessionFile} from './helpers'
test('WEB-AUTH-CROSS003 real late expired response cannot clear a newly authenticated session',async({page,context,request},info)=>{
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.layout.settings',states:['stale_response_discarded']})});test.setTimeout(45_000);const sessions=JSON.parse(readFileSync(sessionFile,'utf8')),expires=Date.now()+10_000,minted=await request.post('/api/auth/tokens',{...fixtureApi('athleteB'),data:{name:'Synthetic stale-response QA',expiresAt:new Date(expires).toISOString()}});expect(minted.status()).toBe(201);const token=await minted.json(),oldSession={token:token.token,tokenId:token.tokenId,user:sessions.athleteB.user};let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),held=new Promise<void>(resolve=>entered=resolve);let first=true,lateStatus:number|null=null,recovered:any=null
 await page.route('**/api/auth/me',async route=>{if(!first)return route.continue();first=false;entered();await gate;const response=await route.fetch();lateStatus=response.status();await route.fulfill({response})})
 try{await page.addInitScript(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},oldSession);await page.goto('/');await expect(page.locator('.page-title')).toHaveText('Hey Synthetic');if(await page.getByRole('button',{name:'Menu',exact:true}).isVisible())await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByTitle('Settings',{exact:true}).click();await held;const other=await context.newPage();await other.goto('/src/styles/coach.css');await other.evaluate(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},sessions.athlete);await other.close();await expect(page.getByLabel('Username',{exact:true})).toBeVisible();await page.getByLabel('Username',{exact:true}).fill(accounts.athleteB.username);await page.getByLabel('Password',{exact:true}).fill(accounts.athleteB.password);const loginResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/auth/login');await page.getByRole('button',{name:'Sign in',exact:true}).click();expect((await loginResponse).status()).toBe(200);await expect(page.locator('.page-title')).toHaveText('Hey Synthetic');recovered=await page.evaluate(()=>({token:localStorage.getItem('loopback.token'),tokenId:localStorage.getItem('loopback.tokenId'),user:JSON.parse(localStorage.getItem('loopback.user')||'null')}));expect(recovered.user.id).toBe(sessions.athleteB.user.id)
 const late=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/auth/me'&&response.status()===401);await page.waitForTimeout(Math.max(0,expires-Date.now()+500));release();await late;await expect.poll(()=>lateStatus).toBe(401);await expect(page.locator('.page-title')).toHaveText('Hey Synthetic');await expect(page.getByLabel('Username',{exact:true})).toHaveCount(0);expect(await page.evaluate(id=>localStorage.getItem('loopback.tokenId')===id,recovered.tokenId)).toBe(true);const me=await request.get('/api/auth/me',{headers:{Authorization:`Bearer ${recovered.token}`}});expect(me.status()).toBe(200);expect((await me.json()).user.id).toBe(sessions.athleteB.user.id)
 }finally{release();for(const tokenId of [oldSession.tokenId,recovered?.tokenId].filter(Boolean)){const removed=await request.delete(`/api/auth/tokens/${tokenId}`,fixtureApi('athleteB'));expect([204,404]).toContain(removed.status())}}
})
