import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import path from 'node:path'
import {screenshot} from './helpers'
const lines=readFileSync(path.resolve('../../../artifacts/baseline-server/bootstrap-qa/private.env'),'utf8').split(/\r?\n/)
const field=(key:string)=>lines.find(line=>line.startsWith(key+'='))!.slice(key.length+1).replace(/^['"]|['"]$/g,'')
test('WEB-AUTH-BOOTSTRAP-001 fresh first-run form validates and creates exactly one private admin',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'AUTH-001'})
 for(const [id,states] of Object.entries({'web.login.username':['setup','blank','whitespace'],'web.login.password':['setup','invalid','inflight'],'web.login.display-name':['setup'],'web.login.confirm-password':['setup','mismatch'],'web.login.submit':['setup','inflight','rate-limited','offline']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 expect((await (await request.get('/api/auth/setup')).json()).required).toBeTruthy();await page.goto('/login');await expect(page.getByText('Create your admin account',{exact:true})).toBeVisible();await screenshot(page,info.project.name,'fresh-bootstrap-empty')
 const username=page.getByLabel('Username',{exact:true}),password=page.getByLabel('Password',{exact:true}),confirm=page.getByLabel('Confirm password',{exact:true}),submit=page.getByRole('button',{name:'Create admin account',exact:true})
 await username.fill('');await password.fill('short');await confirm.fill('short');await submit.click();expect((await (await request.get('/api/auth/setup')).json()).required).toBeTruthy();await username.fill('   ');await password.fill(field('QA_PASSWORD'));await confirm.fill(field('QA_PASSWORD'));await submit.click();await expect(page.getByRole('alert')).toContainText('Pick a username');await username.fill(field('QA_USERNAME'));await confirm.fill('Synthetic mismatched value');await submit.click();await expect(page.getByRole('alert')).toContainText('Passwords do not match');await confirm.fill(field('QA_PASSWORD'));await page.getByLabel('Display name (optional)',{exact:true}).fill('Synthetic bootstrap café')
 await page.route('**/api/auth/setup',route=>route.request().method()==='POST'?route.fulfill({status:429,contentType:'application/json',body:JSON.stringify({detail:'Synthetic rate limit'})}):route.continue());await submit.click();await expect(page.getByRole('alert')).toContainText('Too many attempts');await page.unroute('**/api/auth/setup')
 await page.route('**/api/auth/setup',route=>route.request().method()==='POST'?route.abort('connectionfailed'):route.continue());await submit.click();await expect(page.getByRole('alert')).toContainText('server reachable');await page.unroute('**/api/auth/setup');expect((await (await request.get('/api/auth/setup')).json()).required).toBeTruthy()
 let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/api/auth/setup',async route=>{if(route.request().method()==='POST')await gate;await route.continue()});const response=page.waitForResponse(r=>r.url().endsWith('/api/auth/setup')&&r.request().method()==='POST');await submit.click();await expect(page.getByRole('button',{name:'Creating account…',exact:true})).toBeDisabled();release();const result=await response;expect(result.status()).toBe(200);const session=await result.json();await expect(page).not.toHaveURL(/\/login$/);expect((await (await request.get('/api/auth/setup')).json()).required).toBeFalsy();const me=await request.get('/api/auth/me',{headers:{Authorization:`Bearer ${session.token}`}});expect(me.ok()).toBeTruthy();expect((await me.json()).user).toMatchObject({username:field('QA_USERNAME'),role:'admin',displayName:'Synthetic bootstrap café'});await page.reload();await expect(page.locator('.page-title')).toHaveText('User management')
})
test('WEB-AUTH-BOOTSTRAP-002 stale first-run page handles real setup conflict and authenticates existing admin',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'AUTH-001'},{type:'control',description:JSON.stringify({id:'web.login.submit',states:['setup-conflict','login']})})
 expect((await (await request.get('/api/auth/setup')).json()).required).toBeFalsy()
 // Only the first-run status projection is delayed/stale; POST goes to real already-bootstrapped backend.
 await page.route('**/api/auth/setup',route=>route.request().method()==='GET'?route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({required:true})}):route.continue())
 await page.goto('/login');await page.getByLabel('Username',{exact:true}).fill(field('QA_USERNAME'));await page.getByLabel('Password',{exact:true}).fill(field('QA_PASSWORD'));await page.getByLabel('Confirm password',{exact:true}).fill(field('QA_PASSWORD'));const response=page.waitForResponse(r=>r.url().endsWith('/api/auth/setup')&&r.request().method()==='POST');await page.getByRole('button',{name:'Create admin account',exact:true}).click();expect((await response).status()).toBe(409);await expect(page.getByRole('alert')).toContainText('Setup is already complete');await expect(page.getByLabel('Password',{exact:true})).toHaveValue('');await expect(page.getByLabel('Confirm password',{exact:true})).toHaveCount(0);await page.unroute('**/api/auth/setup');await page.getByLabel('Password',{exact:true}).fill(field('QA_PASSWORD'));const usersResponse=page.waitForResponse(r=>r.url().endsWith('/api/admin/users'));await page.getByRole('button',{name:'Sign in',exact:true}).click();const rows=await (await usersResponse).json();expect(rows.filter((u:{username:string})=>u.username===field('QA_USERNAME'))).toHaveLength(1);await expect(page.locator('.page-title')).toHaveText('User management');await expect(page.locator('.u-row')).toHaveCount(rows.length);await page.reload();await expect(page.locator('.u-row')).toHaveCount(rows.length);await expect(page.getByText('Synthetic bootstrap café',{exact:true})).toBeVisible()
})
