import {test,expect} from '@playwright/test'
import {useFixtureSession,fixtureApi} from './helpers'
const types=[['running','Running'],['traditionalStrength','Strength'],['flexibility','Flexibility'],['walking','Walking'],['cycling','Cycling'],['snowboarding','Snowboarding'],['elliptical','Elliptical'],['rowing','Rowing'],['mixedCardio','Mixed cardio'],['other','Other']]
test('WEB-BROWSE-001 each workout filter matches real API and repeat preserves rows',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-015'},{type:'control',description:JSON.stringify({id:'web.workouts.filter-type',states:types.map(([type])=>type)})})
 await useFixtureSession(page,'athlete');await page.goto('/workouts');await expect(page.locator('.wo-row').first()).toBeVisible()
 for(const [type,label] of types){const result=await request.get(`/api/workouts?activity_type=${type}&limit=50&offset=0`,fixtureApi('athlete'));expect(result.ok()).toBeTruthy();const rows=await result.json();await page.getByRole('button',{name:label,exact:true}).click();await expect(page.locator('.wo-row')).toHaveCount(rows.length);expect(await page.locator('.wo-row').evaluateAll(elements=>elements.map(el=>el.getAttribute('data-workout-id')))).toEqual(rows.map((r:{id:string})=>r.id));if(rows.length){await expect(page.locator('.wo-name').first()).toHaveText(label)}else await expect(page.getByText('No workouts yet',{exact:true})).toBeVisible();await page.getByRole('button',{name:label,exact:true}).click();await expect(page.locator('.wo-row')).toHaveCount(rows.length)}
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.workouts.filter-all',states:['populated']})});await page.getByRole('button',{name:'All',exact:true}).click();await expect(page.locator('.wo-row').first()).toBeVisible();await page.reload();await expect(page.getByRole('button',{name:'All',exact:true})).toHaveClass(/on/)
})
test('WEB-BROWSE-002 calendar month and week navigation request correct distinct ranges',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-015'})
 for(const id of ['month','week','previous-month','next-month','previous-week','next-week'])info.annotations.push({type:'control',description:JSON.stringify({id:`web.calendar.${id}`,states:id==='previous-month'||id==='next-month'?['year-boundary']:id==='previous-week'||id==='next-week'?['week-view']:['default']})})
 const calls:string[]=[];page.on('request',r=>{if(r.url().includes('/api/schedule/calendar'))calls.push(r.url())})
 await useFixtureSession(page,'athlete');await page.goto('/calendar');await expect(page.locator('.month-name')).toBeVisible();const original=await page.locator('.month-name').innerText()
 for(let i=0;i<13;i++){await page.getByRole('button',{name:'Previous month',exact:true}).click();await expect(page.getByText('Loading schedule…',{exact:true})).toHaveCount(0)}await expect(page.locator('.month-name')).not.toHaveText(original);for(let i=0;i<13;i++){await page.getByRole('button',{name:'Next month',exact:true}).click();await expect(page.getByText('Loading schedule…',{exact:true})).toHaveCount(0)}await expect(page.locator('.month-name')).toHaveText(original)
 await page.getByRole('button',{name:'Week',exact:true}).click();await expect(page.locator('.cal-month-card')).toHaveCount(0);await page.getByRole('button',{name:'Prev',exact:true}).click();await expect(page.getByText('Loading schedule…',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByRole('button',{name:'Month',exact:true}).click();await expect(page.locator('.month-name')).toHaveText(original)
 expect(new Set(calls).size).toBeGreaterThanOrEqual(3);for(const url of new Set(calls)){const endpoint=new URL(url);const from=endpoint.searchParams.get('from'),to=endpoint.searchParams.get('to');expect(from).toMatch(/^\d{4}-\d{2}-\d{2}$/);expect(to).toMatch(/^\d{4}-\d{2}-\d{2}$/);expect(from!<=to!).toBeTruthy();const response=await request.get(endpoint.pathname+endpoint.search,fixtureApi('athlete'));expect(response.ok()).toBeTruthy();expect(Array.isArray((await response.json()).entries)).toBeTruthy()}
})
test('WEB-BROWSE-003 workout pagination appends exact next page once and row opens correct record',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-015'})
 for(const [id,states] of Object.entries({'web.workouts.load-more':['more-than-50','inflight','end'],'web.workouts.row':['first','last','distinct-identity']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const get=async(offset:number)=>{const result=await request.get(`/api/workouts?limit=50&offset=${offset}`,fixtureApi('athlete'));expect(result.ok()).toBeTruthy();return await result.json()};const first=await get(0),second=await get(50);expect(first.length).toBe(50);expect(second.length).toBeGreaterThan(0)
 await useFixtureSession(page,'athlete');await page.goto('/workouts');await expect(page.locator('.wo-row')).toHaveCount(first.length);const load=page.getByRole('button',{name:'Load more',exact:true});let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/api/workouts?*',async route=>{if(new URL(route.request().url()).searchParams.get('offset')==='50')await gate;await route.continue()});await load.click();await expect(page.getByRole('button',{name:'Loading…',exact:true})).toBeDisabled();release();await expect(page.locator('.wo-row')).toHaveCount(first.length+second.length);expect(await page.locator('.wo-row').evaluateAll(rows=>rows.map(row=>row.getAttribute('data-workout-id')))).toEqual([...first,...second].map((r:{id:string})=>r.id))
 if(second.length<50)await expect(load).toHaveCount(0)
 for(const record of [second.at(-1),first[0]]){const row=page.locator(`[data-workout-id="${record.id}"]`);await row.focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(new RegExp(`/workouts/${record.id}$`));const detail=await request.get(`/api/workouts/${record.id}`,fixtureApi('athlete'));expect(detail.ok()).toBeTruthy();expect((await detail.json()).id).toBe(record.id);await page.getByRole('button',{name:'Back',exact:true}).click();await expect(page).toHaveURL(/\/workouts$/)}
})
