import {test,expect} from '@playwright/test'
import {useFixtureSession,fixtureApi} from './helpers'
const dateLabel=(date:string)=>`${Number(date.slice(8,10))} ${new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'short'}).toUpperCase()}`
const hours=(seconds:number)=>{const minutes=Math.round(seconds/60);return `${Math.floor(minutes/60)}:${String(minutes%60).padStart(2,'0')}`}
test('WEB-CHART002 every health and nutrition chart matches canonical first middle last values and real pointer/touch selection',async({page,request},info)=>{
 test.setTimeout(90_000);await useFixtureSession(page,'athlete');await page.goto('/health');const start=await page.evaluate(()=>{const date=new Date();date.setDate(date.getDate()-30);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`})
 const fetchRows=async(path:string)=>{const response=await request.get(path,fixtureApi('athlete'));expect(response.status()).toBe(200);return response.json()}
 const metrics=(await fetchRows(`/api/health/metrics?start_date=${start}`)).reverse(),nutrition=(await fetchRows(`/api/nutrition?start_date=${start}`)).reverse(),summary=await fetchRows(`/api/nutrition/summary?start_date=${start}&period=week&timezone=Australia%2FBrisbane`)
 const nearestWeight=(index:number)=>{for(let distance=0;distance<metrics.length;distance++){for(const i of [index-distance,index+distance])if(i>=0&&i<metrics.length&&metrics[i].weight!=null)return metrics[i]}throw Error('Fixture has no weight')}
 const charts=[
 {name:'Recovery history',id:'recovery',point:true,rows:metrics,expected:(row:any)=>`${Math.round(row.resting_heart_rate)} bpm`},
 {name:'Sleep history',id:'sleep',rows:metrics.filter((row:any)=>row.sleep_duration!=null||row.sleep_stages!=null),expected:(row:any)=>row.sleep_duration==null?'—':hours(row.sleep_duration)},
 {name:'Weight history',id:'weight',point:true,rows:metrics,selected:(row:any,index:number)=>nearestWeight(index),expected:(row:any)=>`${row.weight.toFixed(1)} kg`},
 {name:'Steps history',id:'steps',rows:metrics.filter((row:any)=>row.steps!=null),expected:(row:any)=>Math.round(row.steps).toLocaleString('en-US')},
 {name:'Nutrition macros',id:'nutrition-macros',rows:nutrition.filter((row:any)=>['protein_g','carbs_g','fat_g'].some(key=>row[key]!=null)).slice(-30),expected:(row:any)=>`${Math.round(row.protein_g)} g`},
 {name:'Energy balance',id:'energy-balance',rows:nutrition.filter((row:any)=>row.energy_kcal!=null).slice(-30),expected:(row:any)=>`${Math.round(row.energy_kcal)} kcal`},
 {name:'Protein per kilogram',id:'protein-per-kilogram',point:true,rows:summary.periods.filter((row:any)=>row.protein_g_per_kg!=null).slice(0,52).reverse(),expected:(row:any)=>`${row.protein_g_per_kg.toFixed(2)} g/kg`},
 ]
 for(const spec of charts){expect(spec.rows.length,`synthetic fixture ${spec.name} denominator`).toBeGreaterThan(2);const chart=page.getByRole('group',{name:spec.name,exact:true});await chart.scrollIntoViewIfNeeded();await chart.focus();const tooltip=chart.getByRole('tooltip');const assertRow=async(index:number)=>{const row=spec.selected?spec.selected(spec.rows[index],index):spec.rows[index];await expect(tooltip).toContainText(spec.expected(row));await expect(tooltip).toContainText(dateLabel(row.date||row.period_start))}
 for(const index of [0,Math.floor(spec.rows.length/2),spec.rows.length-1]){await chart.focus();await page.keyboard.press('Home');for(let i=0;i<index;i++)await page.keyboard.press('ArrowRight');await assertRow(index)}
 await page.keyboard.press('Escape');await expect(tooltip).toHaveCount(0);const box=await chart.boundingBox();expect(box).not.toBeNull();const mid=Math.floor(spec.rows.length/2),fraction=spec.point?mid/(spec.rows.length-1):(mid+.5)/spec.rows.length,x=box!.x+box!.width*fraction,y=box!.y+box!.height/2
 const states=['first','middle','last']
 if(info.project.use.hasTouch){await page.touchscreen.tap(x,y);await assertRow(mid);states.push('touch')}else{await page.mouse.move(x,y);await assertRow(mid);await page.mouse.move(box!.x+box!.width+8,y);await expect(tooltip).toHaveCount(0);states.push('pointer-leave')}
 info.annotations.push({type:'control',description:JSON.stringify({id:`web.health.chart-${spec.id}`,states})})
 }
})

test('WEB-CHART003 empty synthetic account shows unknown data instead of zero-valued charts',async({page,request},info)=>{
 const options=fixtureApi('athleteB');for(const path of ['/api/health/metrics','/api/nutrition']){const response=await request.get(path+'?start_date=2020-01-01',options);expect(response.status()).toBe(200);expect(await response.json()).toEqual([])}
 await useFixtureSession(page,'athleteB');await page.goto('/health');await expect(page.getByText('No health data in this range',{exact:true})).toBeVisible();await expect(page.getByRole('group',{name:/history|Nutrition macros|Energy balance|Protein per kilogram/})).toHaveCount(0);await expect(page.locator('.page-subtitle')).toHaveText('0 days of metrics in range');await page.reload();await expect(page.getByText('No health data in this range',{exact:true})).toBeVisible();
 for(const id of ['recovery','sleep','weight','steps','nutrition-macros','energy-balance','protein-per-kilogram'])info.annotations.push({type:'control',description:JSON.stringify({id:`web.health.chart-${id}`,states:['empty_dataset']})})
})
test('WEB-CHART004 persistent sparse observations remain unknown and omitted samples are never fabricated',async({page,request},info)=>{
 test.setTimeout(60_000);const username=`web-chart-${crypto.randomUUID().slice(0,8)}`,password=`qa-secret-${crypto.randomUUID()}`,admin=fixtureApi('admin');const created=await request.post('/api/admin/users',{...admin,data:{username,password,displayName:'Synthetic chart gaps',role:'user'}});expect(created.status()).toBe(201);const actor=await created.json()
 try{const login=await request.post('/api/auth/login',{data:{username,password,deviceName:'Synthetic sparse chart QA'}});expect(login.status()).toBe(200);const session=await login.json(),options={headers:{Authorization:`Bearer ${session.token}`}};const dates=await page.evaluate(()=>[28,14,2].map(offset=>{const date=new Date();date.setDate(date.getDate()-offset);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}))
 const metrics=[{date:dates[0],restingHeartRate:61,hrvSdnn:51,weight:70,steps:8000,sleepDuration:25200,activeEnergyBurned:500,basalEnergyBurned:1800},{date:dates[1],sleepStages:{deep:3600},activeEnergyBurned:450},{date:dates[2],restingHeartRate:59,hrvSdnn:54,weight:71,steps:9200,sleepDuration:27000,activeEnergyBurned:600,basalEnergyBurned:1800}];expect((await request.post('/api/health/metrics',{...options,data:{metrics}})).status()).toBe(200);expect((await request.post('/api/nutrition',{...options,data:{days:[{date:dates[0],energyKcal:2100,proteinG:100,carbsG:220,fatG:60},{date:dates[1],energyKcal:1900,carbsG:180},{date:dates[2],energyKcal:2300,proteinG:110,carbsG:250,fatG:70}]}})).status()).toBe(200)
 const recorded=await request.get(`/api/health/metrics?start_date=${dates[0]}`,options);expect(recorded.status()).toBe(200);const rows=await recorded.json();expect(rows.find((row:any)=>row.date===dates[1])).toMatchObject({resting_heart_rate:null,hrv_sdnn:null,weight:null,steps:null,sleep_duration:null,basal_energy_burned:null});const summaryResponse=await request.get(`/api/nutrition/summary?start_date=${dates[0]}&period=week&timezone=Australia%2FBrisbane`,options);expect(summaryResponse.status()).toBe(200);const summary=await summaryResponse.json(),proteinRows=summary.periods.filter((row:any)=>row.protein_g_per_kg!=null).reverse();expect(proteinRows).toHaveLength(2)
 await page.addInitScript(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},session);await page.goto('/health')
 const selected=async(name:string,index:number)=>{const chart=page.getByRole('group',{name,exact:true});await chart.scrollIntoViewIfNeeded();await chart.focus();await page.keyboard.press('Home');for(let i=0;i<index;i++)await page.keyboard.press('ArrowRight');return chart.getByRole('tooltip')}
 const recovery=await selected('Recovery history',1);await expect(recovery).toContainText(dateLabel(dates[1]));await expect(recovery.locator('.tip-row')).toHaveCount(2);await expect(recovery).toContainText('Resting HR—');await expect(recovery).toContainText('HRV—')
 const sleep=await selected('Sleep history',1);await expect(sleep).toContainText(dateLabel(dates[1]));await expect(sleep).toContainText('Asleep—');await expect(sleep).toContainText('Deep1:00')
 const weight=await selected('Weight history',1);await expect(weight).toContainText(dateLabel(dates[0]));await expect(weight).toContainText('70.0 kg');await expect(weight).not.toContainText(dateLabel(dates[1]))
 const steps=await selected('Steps history',1);await expect(steps).toContainText(dateLabel(dates[2]));await expect(steps).toContainText('9,200');await expect(steps).not.toContainText(dateLabel(dates[1]))
 const macros=await selected('Nutrition macros',1);await expect(macros).toContainText(dateLabel(dates[1]));await expect(macros).toContainText('Protein—');await expect(macros).toContainText('Fat—');await expect(macros).toContainText('Carbs180 g')
 const energy=await selected('Energy balance',1);await expect(energy).toContainText(dateLabel(dates[1]));await expect(energy).toContainText('1900 kcal');await expect(energy).toContainText('Resting energy never synced');await expect(energy).not.toContainText('Balance')
 const protein=await selected('Protein per kilogram',1);await expect(protein).toContainText(dateLabel(proteinRows[1].period_start));await expect(protein).toContainText(`${proteinRows[1].protein_g_per_kg.toFixed(2)} g/kg`);await page.reload();await expect(page.locator('.page-subtitle')).toHaveText('3 days of metrics in range')
 for(const id of ['recovery','sleep','weight','steps','nutrition-macros','energy-balance','protein-per-kilogram'])info.annotations.push({type:'control',description:JSON.stringify({id:`web.health.chart-${id}`,states:['missing']})})
 }finally{const retired=await request.patch(`/api/admin/users/${actor.id}`,{...admin,data:{isActive:false}});expect(retired.status()).toBe(200)}
})
