import {fillElapsed} from './elapsed-helpers'
import {writeFileSync,mkdirSync} from 'node:fs'
import {test,expect,type Page} from '@playwright/test'
const profile={goal:{type:'general_fitness'},available_days:['mon'],timezone:'Australia/Brisbane',restrictions:['Stored knee restriction'],benchmark:{level:'established',pace_seconds_per_km:360,weekly_distance_meters:18000,long_run_meters:7000,source:'Stored athlete facts',observed_at:'2026-10-09T00:00:00Z'}}
const status={profile,coverage:{history:'unknown'},metrics:{session_count:0,actual_distance_meters:0,planned_future_session_count:0},jobs:[],proposals:[]}
async function openMockNavigation(page:Page){const menu=page.getByRole('button',{name:'Menu',exact:true});if(await menu.isVisible())await menu.click()}
async function mockSession(page:Page){
 await page.addInitScript(()=>{localStorage.setItem('loopback.token','synthetic-mock-session');localStorage.setItem('loopback.tokenId','mock-token');localStorage.setItem('loopback.user',JSON.stringify({id:'mock-athlete',username:'mock-athlete',displayName:'Mock athlete',role:'user'}))})
 await page.route('**/api/**',route=>{const path=new URL(route.request().url()).pathname;return route.fulfill({status:200,json:path==='/api/health'?{database:'ok',service:'ok'}:path==='/api/schedule/calendar'?{entries:[]}:path==='/api/plan-notes/context'?{notes:[],continuity_hint:'Synthetic unknown coverage'}:path==='/api/auth/setup'?{required:false}:path==='/api/nutrition/summary'?{periods:[]}:[]})})
}
test('WEB-REVIEW-001 status failure blocks editing and saving unknown stored restrictions',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: no real backend persistence claim'})
 await mockSession(page);let writes=0
 await page.route('**/api/coaching/profile',route=>{writes++;return route.fulfill({status:200,json:profile})})
 await page.route('**/api/coaching/status',route=>route.fulfill({status:503,json:{detail:'Synthetic status unavailable'}}))
 await page.goto('/coach');await expect(page.getByRole('alert')).toContainText('Synthetic status unavailable')
 await expect(page.getByLabel('Goal',{exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Save coaching profile',exact:true})).toBeDisabled();expect(writes).toBe(0)
})
test('WEB-REVIEW-002 failed then delayed hydration cannot expose editable inputs',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: injected status failure then recovery'})
 await mockSession(page);let calls=0,release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve)
 await page.route('**/api/coaching/status',async route=>{if(++calls===1)return route.fulfill({status:503,json:{detail:'Synthetic status unavailable'}});await gate;return route.fulfill({status:200,json:status})})
 await page.goto('/coach');await expect(page.getByRole('alert')).toContainText('Synthetic status unavailable')
 await expect(page.getByLabel('Benchmark source',{exact:true})).toBeDisabled()
 await page.getByRole('button',{name:'Refresh status',exact:true}).click()
 try{await expect(page.getByLabel('Benchmark source',{exact:true})).toBeDisabled()}finally{release()}
 await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue('Stored athlete facts');await expect(page.getByLabel('Benchmark source',{exact:true})).toBeEnabled()
 await page.getByLabel('Benchmark source',{exact:true}).fill('Dirty athlete edit');await page.getByRole('button',{name:'Refresh status',exact:true}).click();await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue('Dirty athlete edit')
})
test('WEB-REVIEW-003 proposal validation severity and explanations remain inspectable',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: explicit proposal finding fixture'})
 await mockSession(page)
 const proposal={id:'mock-proposal',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'adjustment',reason:'Synthetic review',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[{severity:'warning',explanation:'Reduce intensity after incomplete recovery.'},{severity:'error',message:'Workout exceeds the available training window.'}]}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}))
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Review coaching proposal',exact:true})
 await expect(dialog).toContainText('warning');await expect(dialog).toContainText('Reduce intensity after incomplete recovery.');await expect(dialog).toContainText('error');await expect(dialog).toContainText('Workout exceeds the available training window.')
})
test('WEB-REVIEW-004 open proposal expires without an unrelated rerender',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: expiry boundary, not server acceptance evidence'})
 await mockSession(page);let approvals=0
 const proposal={id:'expiring-proposal',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'adjustment',reason:'Short lived review',expires_at:new Date(Date.now()+5000).toISOString(),changes:[],validation:[]}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}));await page.route('**/api/coaching/proposals/*/accept',route=>{approvals++;return route.fulfill({status:200,json:{status:'applied'}})})
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click();const approve=page.getByRole('button',{name:'Approve changes',exact:true});await expect(approve).toBeEnabled();await expect(approve).toBeDisabled({timeout:8000});await expect(page.getByRole('alert')).toContainText('expired');expect(approvals).toBe(0)
})
test('WEB-REVIEW-005 structural proposal exposes both full prescriptions and limitations',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: structural display fixture, not persistent mutation evidence'})
 await mockSession(page)
 const step=(value:number)=>({purpose:'work',goal:{type:'distance',unit:'meters',value}})
 const proposal={id:'structural-proposal',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'future_undo',reason:'Restore future prescriptions only',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[],structuralChanges:[{workoutId:'future-workout',title:'Future easy run',before:{title:'Current run',scheduled_date:'2026-11-01T07:00:00+10:00',composition:{blocks:[{iterations:1,steps:[step(6000)]}]}},after:{title:'Restored run',scheduled_date:'2026-11-02T07:00:00+10:00',composition:{blocks:[{iterations:1,steps:[step(4000)]}]}}}],limitations:['Completed sessions remain unchanged.'],excludedWorkoutIds:['protected-workout']}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}))
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click();const before=page.getByRole('region',{name:'Current prescription',exact:true}),after=page.getByRole('region',{name:'Proposed prescription',exact:true});await expect(before).toContainText('Current run');await expect(before).toContainText('6 km');await expect(after).toContainText('Restored run');await expect(after).toContainText('4 km');await expect(page.getByRole('region',{name:'Proposal limitations'})).toContainText('Completed sessions remain unchanged.');await page.getByRole('button',{name:'Close without changes'}).click();await expect(page.getByRole('dialog')).toHaveCount(0)
})
test('WEB-REVIEW-006 unknown rebuild attestations stay false and no proposal enables approval',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: unknown attestation and review-required boundary'})
 await mockSession(page);let body:any=null,accepts=0
 await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{id:'mock-plan',name:'Mock forecast',activity_type:'running',status:'draft',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}}}));await page.route('**/api/plans/mock-plan/schedule',route=>route.fulfill({status:200,json:{schedule:null,sessions:[]}}));await page.route('**/api/coaching/programs/mock-plan',route=>route.fulfill({status:200,json:{forecast:[],forecastApproved:false}}))
 await page.route('**/api/coaching/programs/mock-plan/rebuild',route=>{body=route.request().postDataJSON();return route.fulfill({status:200,json:{status:'review_required',proposal:null,forecast:null,preserved_forecast:[],end_date:'2026-12-01',limitations:['Coverage is unknown.'],options:['Record missing training before requesting another preview.']}})});await page.route('**/api/coaching/proposals/*/accept',route=>{accepts++;return route.fulfill({status:200,json:{}})})
 await page.goto('/plans/mock-plan');await page.getByRole('button',{name:'Rebuild remaining forecast',exact:true}).click();await expect(page.getByLabel('I confirm this interruption occurred')).not.toBeChecked();await expect(page.getByLabel('All completed training in this coverage period is recorded')).not.toBeChecked()
 await page.getByLabel('Interruption start',{exact:true}).fill('2026-10-01');await page.getByLabel('Interruption end',{exact:true}).fill('2026-10-08');await page.getByLabel('Recorded coverage start',{exact:true}).fill('2026-10-01');await page.getByLabel('Recorded coverage end',{exact:true}).fill('2026-10-08');await page.getByRole('button',{name:'Prepare preview',exact:true}).click();await expect(page.getByRole('region',{name:'Rebuild outcome'})).toContainText('review required');expect(body.interruption.confirmed).toBe(false);expect(body.coverage.complete).toBe(false);await expect(page.getByRole('button',{name:'Approve changes',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Cancel without changes',exact:true}).click();expect(accepts).toBe(0)
})
test('WEB-REVIEW-007 proposal evidence separates recorded totals from planned and unknown coverage',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: bounded assessment/metrics display, not real inference evidence'})
 await mockSession(page)
 const proposal={id:'evidence-proposal',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'pace',reason:'Recorded review',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[],evidenceSummary:{paceStatus:'monitoring',independentEligibleDays:1,minimumIndependentDays:3,paceReason:'Easy and unknown-version runs excluded',explicitMissCount:2,elapsedGapDays:9,gapCoverage:'unknown',interruptionReview:true,partialWeekTreatment:'exclude'},coverage:{history:'recorded_only',ingestionCompleteness:'unknown'},metrics:{session_count:2,actual_distance_meters:11000,actual_duration_seconds:3900,planned_future_session_count:4,timezone:'Australia/Brisbane',weeks:{'2026-10-05':{partial_week:true,session_count:2,distance_meters:11000,duration_seconds:3900,unknown_distance_sessions:1,unknown_duration_sessions:0,longest_run_meters:7000,longest_run_share:7/11,hard_session_count:1,hard_session_evidence:'reported_effort_only',planned_session_count:3,planned_distance_meters:18000,planned_duration_seconds:6000,planned_estimated:true,actual_vs_planned_distance_ratio:null,comparison_status:'partial_week_not_compared'}}}}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}))
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click();const evidence=page.getByRole('region',{name:'Training evidence'});await expect(evidence).toContainText('insufficient independent pace evidence');await expect(evidence).toContainText('Recorded totals: 2 sessions');await expect(evidence).toContainText('11 km');await expect(evidence).toContainText('Ingestion completeness: unknown');await expect(evidence).toContainText('4 planned future sessions');await evidence.locator('summary').click();await expect(evidence).toContainText('Unknown distance: 1 sessions');await expect(evidence).toContainText('Actual / planned distance: Not compared');await expect(evidence).toContainText('18 km')
})
test('WEB-REVIEW-008 optional explanation remains an annotation and never accepts prescriptions',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: optional explanation binding, not actual CLI inference'})
 await mockSession(page);let linked:any=null,posts=0,accepts=0
 const proposal={id:'explained-proposal',plan_id:'mock-plan',previewJobId:'source-preview',base_revision:1,status:'awaiting_approval',type:'future_undo',reason:'Deterministic preview',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[]}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}));await page.route('**/api/coaching/jobs',route=>route.fulfill({status:200,json:linked?[linked]:[]}));await page.route('**/api/coaching/jobs/source-preview/explanation',route=>{posts++;expect(route.request().postDataJSON().idempotencyKey).toBeTruthy();linked={id:'explanation-job',status:'pending',attempts:0,data:{previewJobId:'source-preview',trigger:'structural_explanation'},created_at:new Date().toISOString()};return route.fulfill({status:201,json:linked})});await page.route('**/api/coaching/proposals/*/accept',route=>{accepts++;return route.fulfill({status:200,json:{}})})
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click();const region=page.getByRole('region',{name:'Optional coaching explanation'});await region.getByRole('button',{name:'Request CLI explanation',exact:true}).click();await expect(region).toContainText('Explanation job: pending');await expect(region.getByRole('button',{name:'Request CLI explanation',exact:true})).toBeDisabled();expect(posts).toBe(1)
 linked={...linked,status:'completed',attempts:1,data:{...linked.data,explanation:{source:'authenticated-cli',reason:'Synthetic explanation fixture; preserve recovery days.',status:'keep',untrusted_annotation:true}}};await region.getByRole('button',{name:'Refresh explanation',exact:true}).click();await expect(region).toContainText('Untrusted CLI annotation');await expect(region).toContainText('Synthetic explanation fixture; preserve recovery days.');await page.getByRole('button',{name:'Close without changes',exact:true}).click();expect(accepts).toBe(0)
})
test('WEB-REVIEW-009 awaiting initial preview retains its intent after closing',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: preview identity, not persistent backend qualification'})
 await mockSession(page);const keys:string[]=[]
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}));await page.route('**/api/coaching/program',route=>{keys.push(route.request().postDataJSON().idempotencyKey);return route.fulfill({status:201,json:{proposal:{id:'preview-'+keys.length,plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'initial_program',reason:'Fresh intent',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[]}}})})
 await page.goto('/coach');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('button',{name:'Close without changes',exact:true}).click();await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(keys).toHaveLength(2);expect(keys[1]).toBe(keys[0])
})
test('WEB-REVIEW-010 structural pace-only change exposes both intensity ranges',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: intensity comparison'})
 await mockSession(page);const composition=(min:number,max:number)=>({blocks:[{iterations:1,steps:[{purpose:'work',goal:{type:'distance',unit:'meters',value:5000},alert:{type:'speed',unit:'metersPerSecond',min,max}}]}]})
 const proposal={id:'pace-only',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'future_undo',reason:'Pace changed',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[],structuralChanges:[{workoutId:'same-session',title:'Same volume',before:{title:'Current',composition:composition(2.5,3)},after:{title:'Proposed',composition:composition(3,3.5)}}]}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}));await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click();await expect(page.getByRole('region',{name:'Current prescription',exact:true})).toContainText('2.5–3 m/s');await expect(page.getByRole('region',{name:'Proposed prescription',exact:true})).toContainText('3–3.5 m/s')
})
test('WEB-REVIEW-011 changed rebuild dates and new dialog require fresh attestations',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: explicit athlete attestation invalidation'})
 await mockSession(page);await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{id:'mock-plan',name:'Mock forecast',activity_type:'running',status:'draft',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}}}));await page.route('**/api/plans/mock-plan/schedule',route=>route.fulfill({status:200,json:{schedule:null,sessions:[]}}));await page.route('**/api/coaching/programs/mock-plan',route=>route.fulfill({status:200,json:{forecast:[],forecastApproved:false}}))
 await page.goto('/plans/mock-plan');await page.getByRole('button',{name:'Rebuild remaining forecast',exact:true}).click();const interruption=page.getByLabel('I confirm this interruption occurred'),coverage=page.getByLabel('All completed training in this coverage period is recorded');await interruption.check();await coverage.check();await page.getByLabel('Interruption start',{exact:true}).fill('2026-10-01');await expect(interruption).not.toBeChecked();await expect(coverage).toBeChecked();await page.getByLabel('Recorded coverage end',{exact:true}).fill('2026-10-08');await expect(coverage).not.toBeChecked();await interruption.check();await coverage.check();await page.getByRole('button',{name:'Cancel without changes',exact:true}).click();await page.getByRole('button',{name:'Rebuild remaining forecast',exact:true}).click();await expect(interruption).not.toBeChecked();await expect(coverage).not.toBeChecked()
})
test('WEB-REVIEW-012 preview retry survives reload and awaiting success keeps its intent',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: failed request identity across reload, not persistent backend acceptance'})
 await mockSession(page);const keys:string[]=[]
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}));await page.route('**/api/coaching/program',route=>{keys.push(route.request().postDataJSON().idempotencyKey);if(keys.length===1)return route.fulfill({status:503,json:{detail:'Synthetic uncertain preview result'}});return route.fulfill({status:201,json:{proposal:{id:'retry-preview',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'initial_program',reason:'Retry intent',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[]}}})})
 await page.goto('/coach');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Synthetic uncertain preview result');await page.reload();await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue('Stored athlete facts');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(keys[1]).toBe(keys[0]);await page.getByRole('button',{name:'Close without changes',exact:true}).click();await page.reload();await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue('Stored athlete facts');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(keys[2]).toBe(keys[1])
})
test('WEB-REVIEW-013 undo uncertain response reload retries exact original request identity',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: persisted undo response-loss retry'})
 await mockSession(page);const keys:string[]=[];let recovered:any=null
 await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{id:'mock-plan',revision:4,name:'Mock forecast',activity_type:'running',status:'draft',start_date:'2026-11-01',metadata:{}}}));await page.route('**/api/plans/mock-plan/schedule',route=>route.fulfill({status:200,json:{schedule:null,sessions:[]}}));await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:recovered?[recovered]:[]}}));await page.route('**/api/coaching/plans/mock-plan/undo-preview',route=>{keys.push(route.request().postDataJSON().idempotencyKey);recovered={id:'uncertain-undo',plan_id:'mock-plan',base_revision:4,status:'awaiting_approval',type:'future_undo',reason:'Undo retry',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[]};if(keys.length===1)return route.abort('failed');return route.fulfill({status:201,json:{proposal:recovered}})})
 await page.goto('/plans/mock-plan');await page.getByRole('button',{name:'Preview future undo',exact:true}).click();await page.getByLabel('Previous plan revision',{exact:true}).fill('3');await page.getByRole('button',{name:'Prepare preview',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.reload();await page.getByRole('button',{name:'Preview future undo',exact:true}).click();await page.getByLabel('Previous plan revision',{exact:true}).fill('3');await page.getByRole('button',{name:'Prepare preview',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review coaching proposal'})).toBeVisible();expect(keys).toHaveLength(2);expect(keys[1]).toBe(keys[0]);await page.getByRole('button',{name:'Close without changes',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Preview future undo',exact:true}).click();await page.getByLabel('Previous plan revision',{exact:true}).fill('3');await page.getByRole('button',{name:'Prepare preview',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review coaching proposal'})).toBeVisible();expect(keys[2]).toBe(keys[0])
})
test('WEB-REVIEW-014 owned terminal recovered initial proposal ends only its exact request intent',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: recovered terminal request binding, not match by facts'})
 await mockSession(page);const keys:string[]=[];let recovered:any=null
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:recovered?[recovered]:[]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}));await page.route('**/api/coaching/program',async route=>{const key=route.request().postDataJSON().idempotencyKey;keys.push(key);if(keys.length===1){const hash=await page.evaluate(async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,'0')).join(''),key);recovered={id:'terminal-recovered',ownerId:'mock-athlete',clientRequestKeyHash:hash,requestType:'initial_program',requestPlanId:'mock-plan',plan_id:'mock-plan',base_revision:1,status:'dismissed',type:'initial_program',reason:'Recovered terminal request',expires_at:'2030-01-01T00:00:00Z',initialFacts:{idempotencyKey:key},changes:[],validation:[]};return route.abort('failed')}return route.fulfill({status:201,json:{proposal:{...recovered,id:'fresh-after-terminal',status:'awaiting_approval'}}})})
 await page.goto('/coach');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.reload();await expect(page.getByTestId('coaching-proposal-terminal-recovered')).toBeVisible();await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(keys[1]).not.toBe(keys[0])
})
for(const action of ['accept','dismiss'] as const)test(`WEB-REVIEW-015 recovered response then ${action} ends the exact initial preview intent`,async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: recovered response terminal workflow'})
 await mockSession(page);const keys:string[]=[];let recovered:any=null,revision=1,actions=0
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:recovered?[recovered]:[]}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision}}));await page.route('**/api/coaching/proposals/recovered-workflow/'+action,route=>{actions++;recovered.status=action==='accept'?'applied':'dismissed';if(action==='accept'){expect(route.request().postDataJSON().expectedRevision).toBe(1);revision=2}return route.fulfill({status:200,json:{status:recovered.status,planRevision:revision}})});await page.route('**/api/coaching/program',async route=>{const key=route.request().postDataJSON().idempotencyKey;keys.push(key);const hash=await page.evaluate(async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,'0')).join(''),key);const candidate={id:keys.length===1?'recovered-workflow':'new-workflow',ownerId:'mock-athlete',requestType:'initial_program',requestPlanId:'mock-plan',clientRequestKeyHash:hash,plan_id:'mock-plan',base_revision:revision,status:'awaiting_approval',type:'initial_program',reason:'Response-loss fixture',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[]};if(keys.length===1){recovered=candidate;return route.abort('failed')}return route.fulfill({status:201,json:{proposal:candidate}})})
 await page.goto('/coach');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.reload();await page.getByTestId('coaching-proposal-recovered-workflow').getByRole('button',{name:'Review proposal',exact:true}).click();await page.getByRole('button',{name:action==='accept'?'Approve changes':'Dismiss proposal',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await expect(page.getByTestId('coaching-proposal-recovered-workflow')).toContainText(action==='accept'?'applied':'dismissed');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();expect(actions).toBe(1);expect(keys).toHaveLength(2);expect(keys[1]).not.toBe(keys[0])
})
test('WEB-REVIEW-016 rebuild response loss preserves same explicit attestation request through reload',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: rebuild response-loss identity'})
 await mockSession(page);const keys:string[]=[]
 await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{id:'mock-plan',name:'Mock forecast',activity_type:'running',status:'draft',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}}}));await page.route('**/api/plans/mock-plan/schedule',route=>route.fulfill({status:200,json:{schedule:null,sessions:[]}}));await page.route('**/api/coaching/programs/mock-plan',route=>route.fulfill({status:200,json:{forecast:[],forecastApproved:false}}));await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));await page.route('**/api/coaching/programs/mock-plan/rebuild',route=>{const body=route.request().postDataJSON();keys.push(body.idempotencyKey);expect(body.interruption.confirmed).toBe(true);expect(body.coverage.complete).toBe(true);if(keys.length===1)return route.abort('failed');return route.fulfill({status:200,json:{status:'review_required',proposal:null,forecast:null,preserved_forecast:[],end_date:'2026-12-01',limitations:['Review required'],options:[]}})})
 const fill=async()=>{await page.getByRole('button',{name:'Rebuild remaining forecast',exact:true}).click();await expect(page.getByLabel('I confirm this interruption occurred')).not.toBeChecked();await expect(page.getByLabel('All completed training in this coverage period is recorded')).not.toBeChecked();for(const [label,date]of [['Interruption start','2026-10-01'],['Interruption end','2026-10-08'],['Recorded coverage start','2026-10-01'],['Recorded coverage end','2026-10-08']])await page.getByLabel(label,{exact:true}).fill(date);await page.getByLabel('I confirm this interruption occurred').check();await page.getByLabel('All completed training in this coverage period is recorded').check();await page.getByRole('button',{name:'Prepare preview',exact:true}).click()}
 await page.goto('/plans/mock-plan');await fill();await expect(page.getByRole('alert')).toBeVisible();await page.reload();await fill();await expect(page.getByRole('region',{name:'Rebuild outcome'})).toContainText('review required');expect(keys).toHaveLength(2);expect(keys[1]).toBe(keys[0]);await expect(page.getByRole('button',{name:'Approve changes',exact:true})).toHaveCount(0)
})
for(const blockedWrite of ['removeItem','setItem'])for(const revokeStatus of [200,500])test(`WEB-REVIEW-017 blocked optional notice ${blockedWrite} storage cannot prevent logout after revoke ${revokeStatus}`,async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: SecurityError storage and authentication cleanup'})
 await mockSession(page);await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));let revokes=0
 await page.route('**/api/auth/setup',route=>route.fulfill({status:200,json:{required:false}}));await page.route('**/api/auth/tokens/mock-token',route=>{revokes++;return route.fulfill({status:revokeStatus,json:revokeStatus===200?{}:{detail:'Synthetic revoke unavailable'}})})
 await page.goto('/coach');await page.evaluate(blockedWrite=>{for(const method of ['getItem','setItem','removeItem'] as const){const original=Storage.prototype[method];Object.defineProperty(Storage.prototype,method,{configurable:true,value:function(...args:any[]){if(this===sessionStorage&&(method==='getItem'||method===blockedWrite))throw new DOMException('Blocked','SecurityError');return (original as any).apply(this,args)}})}},blockedWrite)
 await openMockNavigation(page);await page.getByTitle('Log out',{exact:true}).click();await expect(page.getByLabel('Username',{exact:true})).toBeVisible();expect(revokes).toBe(1);expect(await page.evaluate(()=>[localStorage.getItem('loopback.token'),localStorage.getItem('loopback.user'),localStorage.getItem('loopback.tokenId')])).toEqual([null,null,null]);await expect(page.getByRole('navigation')).toHaveCount(0);if(revokeStatus===500)await expect(page.getByRole('alert')).toContainText('Could not confirm server session revocation');else await expect(page.getByRole('alert')).toHaveCount(0)
})

test('WEB-REVIEW-018 awaiting rebuild proposal retains exact intent through close and reload',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: rebuild response-loss identity'})
 await mockSession(page);const keys:string[]=[]
 await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{id:'mock-plan',name:'Mock forecast',activity_type:'running',status:'draft',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}}}));await page.route('**/api/plans/mock-plan/schedule',route=>route.fulfill({status:200,json:{schedule:null,sessions:[]}}));await page.route('**/api/coaching/programs/mock-plan',route=>route.fulfill({status:200,json:{forecast:[],forecastApproved:false}}));await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));await page.route('**/api/coaching/programs/mock-plan/rebuild',route=>{const body=route.request().postDataJSON();keys.push(body.idempotencyKey);expect(body.interruption.confirmed).toBe(true);expect(body.coverage.complete).toBe(true);if(keys.length===1)return route.abort('failed');return route.fulfill({status:200,json:{status:'forecast_ready',proposal:{id:'awaiting-rebuild',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'program_rebuild',reason:'Same pending rebuild',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[]},forecast:[],preserved_forecast:[],end_date:'2026-12-01',limitations:['Review required'],options:[]}})})
 const fill=async()=>{await page.getByRole('button',{name:'Rebuild remaining forecast',exact:true}).click();await expect(page.getByLabel('I confirm this interruption occurred')).not.toBeChecked();await expect(page.getByLabel('All completed training in this coverage period is recorded')).not.toBeChecked();for(const [label,date]of [['Interruption start','2026-10-01'],['Interruption end','2026-10-08'],['Recorded coverage start','2026-10-01'],['Recorded coverage end','2026-10-08']])await page.getByLabel(label,{exact:true}).fill(date);await page.getByLabel('I confirm this interruption occurred').check();await page.getByLabel('All completed training in this coverage period is recorded').check();await page.getByRole('button',{name:'Prepare preview',exact:true}).click()}
 await page.goto('/plans/mock-plan');await fill();await expect(page.getByRole('alert')).toBeVisible();await page.reload();await fill();await expect(page.getByRole('dialog',{name:'Review coaching proposal'})).toBeVisible();expect(keys[1]).toBe(keys[0]);await page.getByRole('button',{name:'Close without changes',exact:true}).click();await page.reload();await fill();await expect(page.getByRole('dialog',{name:'Review coaching proposal'})).toBeVisible();expect(keys).toHaveLength(3);expect(keys[2]).toBe(keys[0])
})
test('WEB-REVIEW-019 blocked optional notice storage does not prevent login session adoption',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: SecurityError and successful session adoption'})
 await page.addInitScript(()=>{for(const method of ['getItem','setItem','removeItem'] as const){const original=Storage.prototype[method];Object.defineProperty(Storage.prototype,method,{configurable:true,value:function(...args:any[]){if(this===sessionStorage)throw new DOMException('Blocked','SecurityError');return(original as any).apply(this,args)}})}})
 const pageErrors:string[]=[];page.on('pageerror',error=>pageErrors.push(error.message));let logins=0;await page.route('**/api/**',route=>route.fulfill({status:200,json:new URL(route.request().url()).pathname==='/api/schedule/calendar'?{entries:[]}:new URL(route.request().url()).pathname==='/api/plan-notes/context'?{notes:[],continuity_hint:'Synthetic unknown coverage'}:[]}));await page.route('**/api/auth/setup',route=>route.fulfill({status:200,json:{required:false}}));await page.route('**/api/auth/login',route=>{logins++;return route.fulfill({status:200,json:{token:'synthetic-mock-adopted',tokenId:'mock-adopted-id',user:{id:'mock-new-athlete',username:'mock-new-athlete',displayName:'Mock new athlete',role:'user'}}})})
 await page.goto('/login');await page.getByLabel('Username',{exact:true}).fill('mock-new-athlete');await page.getByLabel('Password',{exact:true}).fill('synthetic-test-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('loopback.user')||'null')?.id)).toBe('mock-new-athlete');expect(logins).toBe(1);await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));await expect(page).not.toHaveURL(/\/login$/);await openMockNavigation(page);await page.getByRole('link',{name:'Coaching',exact:true}).click();await expect(page).toHaveURL(/\/coach$/);await openMockNavigation(page);await expect(page.getByTitle('Log out',{exact:true})).toBeVisible();expect(pageErrors).toEqual([])
})
for(const kind of ['initial','undo','rebuild'] as const)test(`WEB-REVIEW-020 delayed ${kind} preview preparation cannot submit old facts after new session adoption`,async({page,context},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: deliberately delayed crypto preparation and account switch'});const pageErrors:string[]=[];page.on('pageerror',error=>pageErrors.push(error.stack||error.message))
 await mockSession(page);await page.route('**/api/health/metrics**',route=>route.fulfill({status:200,json:[]}));await page.route('**/api/workouts/feedback**',route=>route.fulfill({status:200,json:[]}));const newSession={token:'synthetic-new-session',tokenId:'new-session-id',user:{id:'mock-new-athlete',username:'mock-new-athlete',displayName:'Mock new athlete',role:'user'}};let mixedPosts=0
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));await page.route('**/api/auth/setup',route=>route.fulfill({status:200,json:{required:false}}));await page.route('**/api/auth/login',route=>route.fulfill({status:200,json:newSession}));await page.route('**/api/plan-notes/context',route=>route.fulfill({status:200,json:{notes:[],continuity_hint:'Synthetic unknown coverage'}}));await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{id:'mock-plan',revision:4,name:'Mock forecast',activity_type:'running',status:'draft',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}}}));await page.route('**/api/plans/mock-plan/schedule',route=>route.fulfill({status:200,json:{schedule:null,sessions:[]}}));await page.route('**/api/coaching/programs/mock-plan',route=>route.fulfill({status:200,json:{forecast:[],forecastApproved:false}}));const endpoint=kind==='initial'?'**/api/coaching/program':kind==='undo'?'**/api/coaching/plans/mock-plan/undo-preview':'**/api/coaching/programs/mock-plan/rebuild';await page.route(endpoint,route=>{if(route.request().headers().authorization===`Bearer ${newSession.token}`)mixedPosts++;return route.fulfill({status:409,json:{detail:'Synthetic unsafe request intercepted'}})})
 await page.goto(kind==='initial'?'/coach':'/plans/mock-plan');await page.evaluate(()=>{const original=crypto.subtle.digest.bind(crypto.subtle);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);(window as any).__releaseDigest=()=>release();(window as any).__digestEntered=false;(window as any).__digestCompleted=false;Object.defineProperty(crypto.subtle,'digest',{configurable:true,value:async(...args:any[])=>{(window as any).__digestEntered=true;await gate;const result=await(original as any)(...args);(window as any).__digestCompleted=true;return result}})})
 if(kind==='initial')await page.getByRole('button',{name:'Preview program',exact:true}).click();else{await page.getByRole('button',{name:kind==='undo'?'Preview future undo':'Rebuild remaining forecast',exact:true}).click();if(kind==='undo')await page.getByLabel('Previous plan revision',{exact:true}).fill('3');else for(const [label,date]of [['Interruption start','2026-10-01'],['Interruption end','2026-10-08'],['Recorded coverage start','2026-10-01'],['Recorded coverage end','2026-10-08']])await page.getByLabel(label,{exact:true}).fill(date);await page.getByRole('button',{name:'Prepare preview',exact:true}).click()}
 await expect.poll(()=>page.evaluate(()=>(window as any).__digestEntered)).toBe(true);const other=await context.newPage();await other.goto('/src/styles/coach.css');await other.evaluate(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},newSession);await other.close();await expect(page.getByLabel('Username',{exact:true})).toBeVisible();await page.getByLabel('Username',{exact:true}).fill('mock-new-athlete');await page.getByLabel('Password',{exact:true}).fill('synthetic-test-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();try{await expect(page.locator('.u-name')).toHaveText('Mock new athlete')}catch(error){throw new Error('Replacement login UI failed: '+pageErrors.join('; '),{cause:error})}await page.evaluate(()=>(window as any).__releaseDigest());await expect.poll(()=>page.evaluate(()=>(window as any).__digestCompleted)).toBe(true);await page.waitForTimeout(250);expect(mixedPosts,'Old command must not POST under the newly adopted credential').toBe(0);await expect(page.locator('.u-name')).toHaveText('Mock new athlete')
})
for(const width of [1440,390])for(const mode of ['review_required','compatible','unknown'] as const)test(`WEB-REVIEW-021 current publication ${mode} at ${width}px is visible on plan and coaching without implying committed cancellation`,async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: source-only publicationReview contract'})
 await page.setViewportSize({width,height:900});await mockSession(page);const plan={id:'mock-publication-plan',revision:4,name:'Synthetic current program',activity_type:'running',status:'active',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}},forecast=[{id:'mock-session',date:'2026-11-02',title:'Recorded commitment',status:'pending',prescription_committed:true,composition:{blocks:[{iterations:1,steps:[{purpose:'work',goal:{type:'distance',value:3000,unit:'meters'}}]}]}}];let reads=0,writes=0
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));await page.route('**/api/plans?*',route=>route.fulfill({status:200,json:[plan]}));await page.route('**/api/plans/mock-publication-plan',route=>route.fulfill({status:200,json:plan}));await page.route('**/api/plans/mock-publication-plan/validate',route=>route.fulfill({status:200,json:{warnings:[],weeks:[]}}));await page.route('**/api/plans/mock-publication-plan/schedule',route=>route.fulfill({status:200,json:{schedule:null,sessions:[]}}));await page.route('**/api/coaching/programs/mock-publication-plan',route=>{reads++;if(route.request().method()!=='GET')writes++;return route.fulfill({status:200,json:{forecast,forecastApproved:true,...(mode==='unknown'?{}:{publicationReview:{status:mode,reason:mode==='review_required'?'Current supplied facts need review.':null,restrictions:['Athlete supplied: avoid Saturday sessions <exact>'],availableDays:['mon','wed']}})}})})
 for(const path of ['/plans/mock-publication-plan','/coach']){await page.goto(path);const region=page.getByRole('region',{name:'Full program forecast'});await expect(region).toBeVisible();await expect.poll(()=>reads).toBeGreaterThan(0);await info.attach('publication-region-diagnostic',{body:await region.innerText(),contentType:'text/plain'});if(mode==='review_required'){const notice=region.getByRole('status',{name:'Future issuance paused for review'});await expect(notice).toContainText('Current supplied facts need review.');await expect(notice).toContainText('Athlete supplied: avoid Saturday sessions <exact>');await expect(notice).toContainText('mon, wed');await expect(notice).toContainText('Already committed sessions and history remain recorded.');await expect(notice.getByRole('link')).toHaveAttribute('href',path==='/coach'?'#coaching-facts':'/coach')}else await expect(region.getByRole('status')).toHaveText(mode==='compatible'?'Current publication review is compatible.':'Future issuance review status is unavailable.');await expect(region).toContainText('Recorded commitment');await expect(region).toContainText('Committed · pending');const before=reads;await region.getByRole('button',{name:'Refresh program forecast',exact:true}).click();await expect.poll(()=>reads).toBeGreaterThan(before);await page.reload();await expect(region).toContainText('Recorded commitment');expect(writes).toBe(0);if(mode==='review_required'){mkdirSync('../../../artifacts/web-qa/screenshots/publication-review',{recursive:true});await expect.poll(()=>page.locator('.screen').evaluate(element=>getComputedStyle(element).opacity)).toBe('1');await region.screenshot({animations:'disabled',path:`../../../artifacts/web-qa/screenshots/publication-review/${path.includes('/plans/')?'plan':'coach'}-${width}.png`})}if(mode==='review_required'){const action=region.getByRole('link',{name:'Review coaching facts and request a review',exact:true});await action.focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(path==='/coach'?/\/coach#coaching-facts$/:/\/coach$/);await expect(page.getByLabel('Goal',{exact:true})).toBeVisible();expect(writes).toBe(0)}}
})

const publicationDiagnostics:string[]=[]
test.beforeEach(async({page},info)=>{if(info.title.includes('WEB-REVIEW-021')){publicationDiagnostics.length=0;page.on('request',r=>publicationDiagnostics.push('REQUEST '+new URL(r.url()).pathname));page.on('pageerror',e=>publicationDiagnostics.push('ERROR '+e.message));page.on('console',m=>{if(m.type()==='error')publicationDiagnostics.push('CONSOLE '+m.text())})}})
test.afterEach(async({page},info)=>{if(info.title.includes('WEB-REVIEW-021')&&info.status!==info.expectedStatus)writeFileSync('../../../artifacts/web-qa/publication-fixture-diagnostic.json',JSON.stringify({messages:publicationDiagnostics,body:await page.locator('body').innerText()},null,2))})
for(const count of [0,6,7])test(`WEB-REVIEW-022 profile saves ${count} available days while program preview retains one-to-five limit`,async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: distinct profile and initial program cardinality contracts'})
 await mockSession(page);let saved={...profile},puts=0,previews=0
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,profile:saved}}));await page.route('**/api/coaching/profile',route=>{puts++;saved=route.request().postDataJSON();return route.fulfill({status:200,json:saved})});await page.route('**/api/coaching/program',route=>{previews++;return route.fulfill({status:422,json:{detail:'Synthetic invalid preview cardinality'}})})
 await page.goto('/coach');await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(profile.benchmark.source);for(const day of ['mon','tue','wed','thu','fri','sat','sun']){const button=page.getByRole('button',{name:day,exact:true});if(await button.getAttribute('aria-pressed')==='true')await button.click()}for(const day of ['mon','tue','wed','thu','fri','sat','sun'].slice(0,count))await page.getByRole('button',{name:day,exact:true}).click();await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Coaching profile saved.'})).toBeVisible();expect(puts).toBe(1);expect(saved.available_days).toEqual(['mon','tue','wed','thu','fri','sat','sun'].slice(0,count));expect(saved.restrictions).toEqual(profile.restrictions);await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Choose one to five training days.');expect(previews).toBe(0)
})
test('WEB-REVIEW-023 availability and source edits preserve untouched benchmark precision and provenance',async({page})=>{
 await mockSession(page);let stored:any={...profile,benchmark:{...profile.benchmark,pace_seconds_per_km:360.375,weekly_distance_meters:18000.125,long_run_meters:7000.375,source:'  Exact supplied provenance  ',observed_at:'2026-10-08T12:34:56.789+10:00',confidence:0.76543}};const original=structuredClone(stored.benchmark)
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,profile:stored}}));await page.route('**/api/coaching/profile',route=>{stored=route.request().postDataJSON();return route.fulfill({status:200,json:stored})})
 await page.goto('/coach');await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(original.source);await page.getByRole('button',{name:'tue',exact:true}).click();await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect(stored.benchmark).toEqual(original);await page.reload();await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(original.source)
 await page.getByLabel('Benchmark source',{exact:true}).fill('Edited explicit provenance');await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect(stored.benchmark).toEqual({...original,source:'Edited explicit provenance'})
 await fillElapsed(page,'Current pace','6:01',true);await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect(stored.benchmark.pace_seconds_per_km).toBe(361);expect(stored.benchmark.observed_at).toBe(original.observed_at)
})
test('WEB-REVIEW-024 cached plan Back clears previous plan forms attestations and proposal',async({page})=>{
 await mockSession(page);const plans=['cache-a','cache-b'].map(id=>({id,name:id,revision:2,activity_type:'running',status:'draft',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}}));let approvals=0
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));for(const plan of plans){await page.route(`**/api/plans/${plan.id}`,route=>route.fulfill({status:200,json:plan}));await page.route(`**/api/plans/${plan.id}/schedule`,route=>route.fulfill({status:200,json:{sessions:[],schedule:null}}));await page.route(`**/api/plans/${plan.id}/workouts`,route=>route.fulfill({status:200,json:[]}));await page.route(`**/api/coaching/programs/${plan.id}`,route=>route.fulfill({status:200,json:{forecast:[],forecastApproved:false}}))}
 await page.route('**/api/coaching/plans/cache-b/undo-preview',route=>route.fulfill({status:200,json:{proposal:{id:'cache-b-proposal',plan_id:'cache-b',base_revision:2,status:'awaiting_approval',type:'future_undo',reason:'Only cache B',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[]}}}));await page.route('**/api/coaching/proposals/*/accept',route=>{approvals++;return route.fulfill({status:200,json:{}})})
 await page.goto('/plans/cache-a');await expect(page.getByRole('heading',{name:'Future plan changes'})).toBeVisible();await page.evaluate(()=>{history.pushState(null,'','/plans/cache-b');dispatchEvent(new PopStateEvent('popstate'))});await expect(page).toHaveURL(/cache-b$/);await page.getByRole('button',{name:'Preview future undo',exact:true}).click();await page.getByLabel('Previous plan revision').fill('1');await page.getByRole('button',{name:'Prepare preview',exact:true}).click();await expect(page.getByRole('dialog',{name:'Review coaching proposal'})).toContainText('Only cache B');await page.goBack();await expect(page).toHaveURL(/cache-a$/);await expect(page.getByRole('dialog')).toHaveCount(0);expect(approvals).toBe(0)
 await page.getByRole('button',{name:'Rebuild remaining forecast',exact:true}).click();await page.getByLabel('Interruption start').fill('2026-10-01');await page.getByLabel('Interruption end').fill('2026-10-02');await page.getByLabel('I confirm this interruption occurred').check();await page.goForward();await expect(page).toHaveURL(/cache-b$/);await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByRole('button',{name:'Rebuild remaining forecast',exact:true}).click();await expect(page.getByLabel('Interruption start')).toHaveValue('');await expect(page.getByLabel('I confirm this interruption occurred')).not.toBeChecked();expect(approvals).toBe(0)
})
test('WEB-REVIEW-025 changing cached plan while preview preparation waits cannot send departed plan request',async({page})=>{
 await mockSession(page);await page.addInitScript(()=>{const digest=crypto.subtle.digest.bind(crypto.subtle);let release!:()=>void;(window as any).__previewGate=new Promise<void>(resolve=>release=resolve);(window as any).__releasePreview=release;crypto.subtle.digest=async(...args:Parameters<typeof crypto.subtle.digest>)=>{await(window as any).__previewGate;return digest(...args)}});let requests=0
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));for(const id of ['pending-a','pending-b']){await page.route(`**/api/plans/${id}`,route=>route.fulfill({status:200,json:{id,name:id,revision:2,activity_type:'running',status:'draft',start_date:'2026-11-01',end_date:'2026-12-01',metadata:{forecast:[]}}}));await page.route(`**/api/plans/${id}/schedule`,route=>route.fulfill({status:200,json:{sessions:[],schedule:null}}));await page.route(`**/api/coaching/programs/${id}`,route=>route.fulfill({status:200,json:{forecast:[],forecastApproved:false}}))}
 await page.route('**/api/coaching/plans/pending-b/undo-preview',route=>{requests++;return route.fulfill({status:409,json:{detail:'Departed request intercepted'}})})
 await page.goto('/plans/pending-a');await expect(page.getByRole('heading',{name:'Future plan changes'})).toBeVisible();await page.evaluate(()=>{history.pushState(null,'','/plans/pending-b');dispatchEvent(new PopStateEvent('popstate'))});await page.getByRole('button',{name:'Preview future undo',exact:true}).click();await page.getByLabel('Previous plan revision').fill('1');await page.getByRole('button',{name:'Prepare preview',exact:true}).click();await expect(page.getByRole('button',{name:'Preparing preview…',exact:true})).toBeDisabled();await page.goBack();await expect(page).toHaveURL(/pending-a$/);await page.evaluate(()=>(window as any).__releasePreview());await page.getByRole('button',{name:'Preview future undo',exact:true}).click();await expect(page.getByLabel('Previous plan revision')).toHaveValue('');await page.getByRole('button',{name:'Cancel without changes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(requests).toBe(0)
})
test('WEB-REVIEW-026 departed Coaching cannot submit a delayed same-account preview',async({page})=>{
 await mockSession(page);await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:status}));let posts=0;await page.route('**/api/coaching/program',route=>{posts++;return route.fulfill({status:409,json:{detail:'Departed preview intercepted'}})})
 await page.goto('/coach/');await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(profile.benchmark.source);await page.evaluate(()=>{const digest=crypto.subtle.digest.bind(crypto.subtle);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);(window as any).__releaseDigest=release;(window as any).__entered=false;(window as any).__completed=false;Object.defineProperty(crypto.subtle,'digest',{configurable:true,value:async(...args:any[])=>{(window as any).__entered=true;await gate;const value=await(digest as any)(...args);(window as any).__completed=true;return value}})});await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__entered)).toBe(true);await openMockNavigation(page);await page.getByRole('link',{name:'Plans',exact:true}).click();await expect(page).toHaveURL(/\/plans$/);await page.evaluate(()=>(window as any).__releaseDigest());await expect.poll(()=>page.evaluate(()=>(window as any).__completed)).toBe(true);await page.waitForTimeout(250);expect(posts).toBe(0);await expect(page.getByRole('dialog')).toHaveCount(0)
})
test('WEB-REVIEW-027 clearing confidence removes the saved optional fact from preview save and reload',async({page})=>{
 await mockSession(page);let stored:any={...profile,benchmark:{...profile.benchmark,confidence:0.85}};const previews:any[]=[];await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,profile:stored}}));await page.route('**/api/coaching/profile',route=>{stored=route.request().postDataJSON();return route.fulfill({status:200,json:stored})});await page.route('**/api/coaching/program',route=>{previews.push(route.request().postDataJSON());return route.fulfill({status:409,json:{detail:'Synthetic preview captured'}})})
 await page.goto('/coach');await expect(page.getByLabel('Benchmark confidence (optional, 0–1)',{exact:true})).toHaveValue('0.85');await page.getByLabel('Benchmark confidence (optional, 0–1)',{exact:true}).fill('');await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Synthetic preview captured');expect(previews[0].benchmark).not.toHaveProperty('confidence');await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect(stored.benchmark).not.toHaveProperty('confidence');await page.reload();await expect(page.getByLabel('Benchmark confidence (optional, 0–1)',{exact:true})).toHaveValue('');expect(stored.benchmark.source).toBe(profile.benchmark.source)
})
for(const longest of [7000.375,50.375])test(`WEB-REVIEW-028 valid hydrated fractional facts with longest ${longest} meters submit the native preview form without rounding`,async({page})=>{
 await mockSession(page);const fractional={...profile,benchmark:{...profile.benchmark,confidence:0.85,pace_seconds_per_km:360.375,weekly_distance_meters:12345,long_run_meters:longest,observed_at:'2026-10-08T12:34:56.789+10:00'}};let submitted:any=null
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,profile:fractional}}));await page.route('**/api/coaching/program',route=>{submitted=route.request().postDataJSON();return route.fulfill({status:409,json:{detail:'Synthetic fractional preview captured'}})})
 await page.goto('/coach');await expect(page.getByLabel('Benchmark confidence (optional, 0–1)',{exact:true})).toHaveValue('0.85');await expect(page.getByLabel('Current weekly distance (km)',{exact:true})).toHaveValue('12.345');await expect(page.getByLabel('Current longest run (km)',{exact:true})).toHaveValue(String(longest/1000));await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect.poll(()=>submitted).not.toBeNull();await expect(page.getByRole('alert')).toContainText('Synthetic fractional preview captured');expect(submitted.benchmark).toEqual(fractional.benchmark)
})

for (const sample of [
 {name:'distance',before:{type:'distance',unit:'meters',value:4750},after:{type:'distance',unit:'meters',value:5000},current:'4.75 km',proposed:'5 km'},
 {name:'time',before:{type:'time',unit:'seconds',value:1800},after:{type:'time',unit:'seconds',value:2100},current:'30 min',proposed:'35 min'},
 {name:'open',before:{type:'open'},after:{type:'open'},current:'Open duration',proposed:'Open duration'},
]) test(`WEB-REVIEW-SINGLE001 ${sample.name} single-goal full prescriptions are visible before approval`,async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport; valid legacy singleGoal structural display only, no actual HTTP/persistence/inference claim'})
 await mockSession(page)
 const proposal={id:'single-goal-proposal',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'future_undo',reason:'Synthetic single goal preview',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[],structuralChanges:[{workoutId:'single-goal-workout',title:'Single goal run',before:{title:'Current legacy run',composition:{singleGoal:sample.before}},after:{title:'Proposed legacy run',composition:{singleGoal:sample.after}}}]}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}))
 await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}))
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click()
 await expect(page.getByRole('region',{name:'Current prescription',exact:true})).toContainText(sample.current)
 await expect(page.getByRole('region',{name:'Proposed prescription',exact:true})).toContainText(sample.proposed)
})

test('WEB-REVIEW-SINGLE002 forecast shares single goal display and empty prescriptions remain explicitly unavailable',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: shared forecast rendering and honest unavailable shape'})
 const fixtureErrors:string[]=[]
 page.on('pageerror',error=>fixtureErrors.push(error.message))
 page.on('console',message=>{if(message.type()==='error')fixtureErrors.push(message.text())})
 await mockSession(page)
 const session=(key:string,composition:unknown)=>({id:key,date:'2026-11-01',week:1,title:key,composition})
 const forecast=[session('Legacy timed run',{singleGoal:{type:'time',unit:'seconds',value:1800}}),session('Unknown prescription',{})]
 const proposal={id:'single-forecast',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'program_rebuild',reason:'Synthetic forecast display',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[],forecast}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}))
 await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}))
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click()
 const dialog=page.getByRole('dialog',{name:'Review coaching proposal',exact:true})
 await dialog.getByText('Legacy timed run',{exact:true}).click()
 await expect(dialog.locator('.coach-session').first()).toContainText('Single goal · 30 min')
 await dialog.getByText('Unknown prescription',{exact:true}).click()
 await expect(dialog.locator('.coach-session').nth(1)).toContainText('Prescription details unavailable.')
 expect(fixtureErrors).toEqual([])
})

test('WEB-REVIEW-R124 speed omitted unit uses the verified meters-per-second contract while explicit invalid units stay unavailable',async({page},info)=>{
 info.annotations.push({type:'evidence-layer',description:'mocked transport: backend-supported omitted speed unit display, no HTTP persistence/inference claim'})
 await mockSession(page)
 const composition=(min:number,max:number,unit?:unknown)=>({blocks:[{iterations:1,steps:[{purpose:'work',goal:{type:'distance',unit:'meters',value:5000},alert:{type:'speed',min,max,...(unit===undefined?{}:{unit})}}]}]})
 const proposal={id:'omitted-speed-unit',plan_id:'mock-plan',base_revision:1,status:'awaiting_approval',type:'future_undo',reason:'Synthetic speed unit review',expires_at:'2030-01-01T00:00:00Z',changes:[],validation:[],structuralChanges:[
  {workoutId:'valid-default',title:'Verified default speed',before:{title:'Current default speed',composition:composition(2.5,3)},after:{title:'Proposed default speed',composition:composition(3,3.5)}},
  {workoutId:'unsupported-unit',title:'Explicit unavailable speed unit',before:{title:'Explicit null',composition:composition(2.5,3,null)},after:{title:'Unsupported unit',composition:composition(3,3.5,'milesPerHour')}},
 ]}
 await page.route('**/api/coaching/status',route=>route.fulfill({status:200,json:{...status,proposals:[proposal]}}))
 await page.route('**/api/plans/mock-plan',route=>route.fulfill({status:200,json:{revision:1}}))
 await page.goto('/coach');await page.getByRole('button',{name:'Review proposal',exact:true}).click()
 const current=page.getByRole('region',{name:'Current prescription',exact:true}),proposed=page.getByRole('region',{name:'Proposed prescription',exact:true})
 await expect(current.nth(0)).toContainText('Speed 2.5–3 m/s · Pace 5:33 /km–6:40 /km')
 await expect(proposed.nth(0)).toContainText('Speed 3–3.5 m/s · Pace 4:46 /km–5:33 /km')
 await expect(current.nth(1)).toContainText('Speed alert unit unavailable')
 await expect(proposed.nth(1)).toContainText('Speed alert unit unavailable')
})

test('WEB-REVIEW-SEMANTIC001 elapsed parts preserve exact loaded seconds and optional clear through unrelated edits',async({page},info)=>{
 await mockSession(page);let stored:any={...profile,goal:{type:'general_fitness',target_seconds:90062.375},benchmark:{...profile.benchmark,pace_seconds_per_km:360.375,observed_at:'2026-10-08T12:34:56.789+10:00'}}
 const original=structuredClone(stored)
 await page.route('**/api/coaching/status',r=>r.fulfill({status:200,json:{...status,profile:stored}}))
 await page.route('**/api/coaching/profile',r=>{stored=r.request().postDataJSON();return r.fulfill({status:200,json:stored})})
 await page.goto('/coach')
 for(const [name,value]of [['Target time (optional) hours','25'],['Target time (optional) minutes','1'],['Target time (optional) seconds','2.375'],['Current pace minutes','6'],['Current pace seconds','0.375']])await expect(page.getByLabel(name,{exact:true})).toHaveValue(value)
 await page.getByRole('group',{name:'Target time (optional)',exact:true}).scrollIntoViewIfNeeded();{const capture=info.outputPath('elapsed-loaded-fractional-controls.png');await page.screenshot({path:capture});await info.attach('elapsed-loaded-fractional-controls',{path:capture,contentType:'image/png'})}
 await page.getByLabel('Benchmark source',{exact:true}).fill('Changed source only')
 await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.')
 expect(stored.goal.target_seconds).toBe(original.goal.target_seconds);expect(stored.benchmark.pace_seconds_per_km).toBe(original.benchmark.pace_seconds_per_km);expect(stored.benchmark.observed_at).toBe(original.benchmark.observed_at)
 await page.getByLabel('Current pace seconds',{exact:true}).fill('1.125');await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect(stored.benchmark.pace_seconds_per_km).toBe(361.125)
 await page.getByRole('button',{name:'Clear target time (optional)',exact:true}).click();await page.getByRole('group',{name:'Target time (optional)',exact:true}).scrollIntoViewIfNeeded();{const capture=info.outputPath('elapsed-optional-unknown-controls.png');await page.screenshot({path:capture});await info.attach('elapsed-optional-unknown-controls',{path:capture,contentType:'image/png'})};for(const unit of ['hours','minutes','seconds'])await expect(page.getByLabel(`Target time (optional) ${unit}`,{exact:true})).toHaveValue('')
 await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect(stored.goal).not.toHaveProperty('target_seconds')
})

test('WEB-REVIEW-SEMANTIC002 tiny loaded seconds survive unrelated save and later minute edits',async({page})=>{
 await mockSession(page);let stored:any={...profile,goal:{type:'general_fitness',target_seconds:1e-7},benchmark:{...profile.benchmark,pace_seconds_per_km:1e-7,observed_at:'2026-10-08T12:34:56.789+10:00'}}
 const original=structuredClone(stored)
 await page.route('**/api/coaching/status',r=>r.fulfill({status:200,json:{...status,profile:stored}}))
 await page.route('**/api/coaching/profile',r=>{stored=r.request().postDataJSON();return r.fulfill({status:200,json:stored})})
 await page.goto('/coach')
 for(const label of ['Current pace seconds','Target time (optional) seconds'])await expect(page.getByLabel(label,{exact:true})).toHaveValue('0.0000001')
 await page.getByLabel('Benchmark source',{exact:true}).fill('Tiny precision source edit');await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.')
 expect(stored.goal.target_seconds).toBe(original.goal.target_seconds);expect(stored.benchmark.pace_seconds_per_km).toBe(original.benchmark.pace_seconds_per_km);expect(stored.benchmark.observed_at).toBe(original.benchmark.observed_at)
 await page.getByLabel('Current pace minutes',{exact:true}).fill('1');await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect(stored.benchmark.pace_seconds_per_km).toBe(60+1e-7);expect(stored.goal.target_seconds).toBe(1e-7)
})
