import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {fixtureApi} from './helpers'
test('WEB-LOGIN-001 blank whitespace invalid network rate failure and held keyboard login are truthful',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'AUTH-006'},{type:'scenario',description:'UI-007'},{type:'scenario',description:'UI-010'})
 for(const [id,states]of Object.entries({'web.login.username':['login','blank','whitespace'],'web.login.password':['login','invalid','inflight'],'web.login.submit':['invalid','rate-limited','offline','inflight','keyboard','valid','reload']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const admin=fixtureApi('admin'),username=`web-signin-${randomUUID().slice(0,8)}`,password=`qa-secret-${randomUUID()}`;const created=await request.post('/api/admin/users',{...admin,data:{username,password,displayName:'Synthetic sign in QA',role:'user'}});expect(created.status()).toBe(201);const actor=await created.json()
 try{await page.goto('/login');const name=page.getByLabel('Username',{exact:true}),pass=page.getByLabel('Password',{exact:true}),submit=page.getByRole('button',{name:'Sign in',exact:true});await expect(submit).toBeVisible();let writes=0;page.on('request',r=>{if(r.method()==='POST'&&r.url().endsWith('/api/auth/login'))writes++});await submit.click();await expect(page.getByRole('alert')).toContainText('Invalid username or password');expect(writes).toBe(0);await name.fill('   ');await pass.fill('Synthetic incorrect password');await submit.click();expect(writes).toBe(0)
 await name.fill(username);const denied=page.waitForResponse(r=>r.url().endsWith('/api/auth/login'));await submit.click();expect((await denied).status()).toBe(401);await expect(page).toHaveURL(/\/login$/);expect(await page.evaluate(()=>localStorage.getItem('loopback.token'))).toBeNull()
 await pass.fill(password);await page.route('**/api/auth/login',r=>r.fulfill({status:429,json:{detail:'Synthetic rate limit'}}));await submit.click();await expect(page.getByRole('alert')).toContainText('Too many attempts');expect(await page.evaluate(()=>localStorage.getItem('loopback.token'))).toBeNull();await page.unroute('**/api/auth/login');await page.route('**/api/auth/login',r=>r.abort('connectionrefused'));await submit.click();await expect(page.getByRole('alert')).toContainText('Invalid username or password');await expect(submit).toBeEnabled();await page.unroute('**/api/auth/login')
 let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);let held=0;await page.route('**/api/auth/login',async r=>{held++;await gate;await r.continue()});const authenticated=page.waitForResponse(r=>r.url().endsWith('/api/auth/login')&&r.status()===200);await pass.focus();await page.keyboard.press('Enter');try{await expect(page.getByRole('button',{name:'Signing in…',exact:true})).toBeDisabled();await expect(pass).toHaveAttribute('type','password');await page.keyboard.press('Enter');expect(held).toBe(1)}finally{release()}
 const session=await (await authenticated).json();await expect(page).not.toHaveURL(/\/login$/);const me=await request.get('/api/auth/me',{headers:{Authorization:`Bearer ${session.token}`}});expect((await me.json()).user.id).toBe(actor.id);await page.reload();await expect(page.locator('.page-title')).toHaveText('Hey Synthetic');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('loopback.user')!).id)).toBe(actor.id)
 }finally{await request.patch(`/api/admin/users/${actor.id}`,{...admin,data:{isActive:false}})}
})
