import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import {accounts,fixtureApi,sessionFile} from './helpers'
test('WEB-AUTH-CROSS004 pending old logout cannot clear or warn against a replacement authenticated session',async({page,context,request},info)=>{
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.layout.logout',states:['pending_old_logout_preserves_replacement','stale_logout_warning_discarded']})});const sessions=JSON.parse(readFileSync(sessionFile,'utf8'));const minted=await request.post('/api/auth/tokens',{...fixtureApi('athlete'),data:{name:'Synthetic logout race QA',expiresAt:new Date(Date.now()+120_000).toISOString()}});expect(minted.status()).toBe(201);const ownToken=await minted.json();const oldSession={...ownToken,user:sessions.athlete.user};let release!:()=>void,entered!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),held=new Promise<void>(resolve=>entered=resolve);let recovered:any=null,oldDeleteStatus:number|null=null
 await page.route(`**/api/auth/tokens/${oldSession.tokenId}`,async route=>{entered();await gate;const response=await route.fetch();oldDeleteStatus=response.status();await route.fulfill({response})})
 try{await page.addInitScript(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},oldSession);await page.goto('/');await expect(page.locator('.page-title')).toHaveText('Hey Sofia');if(await page.getByRole('button',{name:'Menu',exact:true}).isVisible())await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByTitle('Log out',{exact:true}).click();await held;const other=await context.newPage();await other.goto('/src/styles/coach.css');await other.evaluate(session=>{localStorage.setItem('loopback.token',session.token);localStorage.setItem('loopback.tokenId',session.tokenId);localStorage.setItem('loopback.user',JSON.stringify(session.user))},sessions.athleteB);await other.close();await expect(page.getByLabel('Username',{exact:true})).toBeVisible();await page.getByLabel('Username',{exact:true}).fill(accounts.athleteB.username);await page.getByLabel('Password',{exact:true}).fill(accounts.athleteB.password);const loginResponse=page.waitForResponse(response=>new URL(response.url()).pathname==='/api/auth/login');await page.getByRole('button',{name:'Sign in',exact:true}).click();expect((await loginResponse).status()).toBe(200);await expect(page.locator('.page-title')).toHaveText('Hey Synthetic');recovered=await page.evaluate(()=>({token:localStorage.getItem('loopback.token'),tokenId:localStorage.getItem('loopback.tokenId')}));release();await expect.poll(()=>oldDeleteStatus).toBe(204);await page.waitForTimeout(150);await expect(page.locator('.page-title')).toHaveText('Hey Synthetic');expect(await page.evaluate(id=>localStorage.getItem('loopback.tokenId')===id,recovered.tokenId)).toBe(true);expect(await page.evaluate(()=>sessionStorage.getItem('loopback.logoutNotice'))).toBeNull();const me=await request.get('/api/auth/me',{headers:{Authorization:`Bearer ${recovered.token}`}});expect(me.status()).toBe(200);expect((await me.json()).user.id).toBe(sessions.athleteB.user.id)
 }finally{release();for(const [tokenId,role]of [[oldSession.tokenId,'athlete'],[recovered?.tokenId,'athleteB']] as const){if(!tokenId)continue;const removed=await request.delete(`/api/auth/tokens/${tokenId}`,fixtureApi(role));expect([204,404]).toContain(removed.status())}}
})
