import {test,expect} from '@playwright/test'
import {useFixtureSession,fixtureApi} from './helpers'
test('WEB-MODAL001 pending token creation cannot dismiss and lose outcome',async({page,request},info)=>{
 for(const [id,states] of Object.entries({'web.settings.token-create':['inflight','failure'],'web.settings.token-cancel':['busy_disabled'],'web.modal.escape-dismiss':['busy'],'web.modal.outside-dismiss':['busy']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB');const tokens=async()=> (await(await request.get('/api/auth/me',auth)).json()).tokens
 const before=(await tokens()).map((row:any)=>row.id);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve)
 await useFixtureSession(page,'athleteB');await page.goto('/settings');await page.getByRole('button',{name:'New token',exact:true}).click();await page.getByLabel('Token name',{exact:true}).fill('Synthetic held token');await page.route('**/api/auth/tokens',async route=>{if(route.request().method()!=='POST')return route.continue();await gate;return route.fulfill({status:500,json:{detail:'Synthetic mint outcome failure'}})})
 const dialog=page.getByRole('dialog',{name:'Create token',exact:true});await dialog.getByRole('button',{name:'Create token',exact:true}).click()
 try{await expect(dialog.getByRole('button',{name:'Creating…',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();await page.locator('.modal-overlay').click({position:{x:2,y:2}});await expect(dialog).toBeVisible()}finally{release()}
 await expect(dialog.getByRole('alert')).toContainText('Synthetic mint outcome failure');await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeEnabled();expect((await tokens()).map((row:any)=>row.id)).toEqual(before);await dialog.getByRole('button',{name:'Cancel',exact:true}).click()
})
test('WEB-MODAL002 pending note save stays open until actual persistent response',async({page,request},info)=>{
 for(const [id,states] of Object.entries({'web.notes.edit-save':['valid','inflight'],'web.notes.edit-cancel':['busy_disabled'],'web.modal.escape-dismiss':['busy'],'web.modal.outside-dismiss':['busy']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB');const response=await request.post('/api/plan-notes',{...auth,data:{kind:'observation',summary:`Synthetic held editor ${Date.now()}`,importance:1}});expect(response.status()).toBe(201);const note=await response.json();let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve)
 try{await useFixtureSession(page,'athleteB');await page.goto('/notes');await page.locator('.note-card').filter({hasText:note.summary}).getByTitle('Edit',{exact:true}).click();await page.getByLabel('Body (optional)',{exact:true}).fill('Persistent held edit');await page.route(`**/api/plan-notes/${note.id}`,async route=>{if(route.request().method()==='PATCH')await gate;return route.continue()});const dialog=page.getByRole('dialog',{name:'Edit note',exact:true});await dialog.getByRole('button',{name:'Save',exact:true}).click();try{await expect(dialog.getByRole('button',{name:'Saving…',exact:true})).toBeDisabled();await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();await page.locator('.modal-overlay').click({position:{x:2,y:2}});await expect(dialog).toBeVisible()}finally{release()}
 await expect(dialog).toHaveCount(0);await page.reload();const saved=(await(await request.get('/api/plan-notes?include_expired=true&limit=200',auth)).json()).find((row:any)=>row.id===note.id);expect(saved.body).toBe('Persistent held edit')
 }finally{release();await request.delete(`/api/plan-notes/${note.id}`,auth)}
})
