import {test,expect} from '@playwright/test'
import {useFixtureSession} from './helpers'
async function openNavigation(page:any){if(await page.getByRole('button',{name:'Menu',exact:true}).isVisible())await page.getByRole('button',{name:'Menu',exact:true}).click()}
test('WEB-NAV001 athlete named routes and settings retain correct identity after reload',async({page,request},info)=>{
 for(const suffix of ['overview','calendar','workouts','plans','notes','health','queue'])info.annotations.push({type:'control',description:JSON.stringify({id:'web.layout.nav-'+suffix,states:['athlete']})})
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.layout.settings',states:['athlete']})},{type:'control',description:JSON.stringify({id:'web.layout.nav-coach',states:['athlete_navigation']})})
 await useFixtureSession(page,'athlete');const user=await page.evaluate(()=>JSON.parse(localStorage.getItem('loopback.user')||'null'))
 for(const [url,title] of [['/calendar','Calendar'],['/workouts','Workouts'],['/plans','Plans'],['/notes','Coach notes'],['/health','Health trends'],['/queue','Watch queue'],['/coach','Coaching'],['/','Hey Sofia']]){await openNavigation(page);await page.locator(`.sidebar-nav a[href="${url}"]`).click();await expect(page.locator('.page-title')).toHaveText(title);await expect(page).toHaveURL(new RegExp(url==='/'?'/$':url+'$'));await expect(page.locator(`.sidebar-nav a[href="${url}"]`)).toHaveAttribute('aria-current','page');await page.reload();await expect(page.locator('.page-title')).toHaveText(title);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('loopback.user')||'null').id)).toBe(user.id)}
 await openNavigation(page);await page.getByTitle('Settings',{exact:true}).click();await expect(page.locator('.page-title')).toHaveText('Settings');await page.reload();await expect(page.locator('.page-title')).toHaveText('Settings');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('loopback.user')||'null').id)).toBe(user.id)
})
test('WEB-NAV002 admin navigation and direct athlete route enforce admin context',async({page},info)=>{
 for(const [id,states] of Object.entries({'web.layout.nav-users':['admin'],'web.layout.nav-system':['admin'],'web.layout.settings':['admin'],'web.layout.nav-coach':['admin_hidden','admin_direct_route_redirect']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 await useFixtureSession(page,'admin');for(const [url,title] of [['/system','System'],['/users','User management']]){await openNavigation(page);await page.locator(`.sidebar-nav a[href="${url}"]`).click();await expect(page.locator('.page-title')).toHaveText(title);await page.reload();await expect(page.locator('.page-title')).toHaveText(title)}
 await expect(page.locator('.sidebar-nav a[href="/coach"]')).toHaveCount(0);await page.goto('/coach');await expect(page).toHaveURL(/\/users$/);await expect(page.locator('.page-title')).toHaveText('User management');await expect(page.getByLabel('Goal',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Attention items',exact:true})).toHaveCount(0);await openNavigation(page);await page.getByTitle('Settings',{exact:true}).click();await expect(page.locator('.page-title')).toHaveText('Settings')
})
test('WEB-NAV003 narrow menu supports keyboard Escape and restores trigger focus',async({page},info)=>{
 test.skip((info.project.use.viewport?.width||0)>860,'Narrow navigation only')
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.layout.menu',states:['narrow','open','escape','focus_trap','restore','aria_expanded']})},{type:'control',description:JSON.stringify({id:'web.layout.scrim',states:['drawer-open','pointer_dismiss']})})
 await useFixtureSession(page,'athlete');const menu=page.getByRole('button',{name:'Menu',exact:true});await menu.focus();await page.keyboard.press('Enter');await expect(page.locator('.sidebar')).toHaveClass(/open/);await expect(page.getByRole('dialog',{name:'Navigation'})).toBeVisible();await expect(menu).toHaveAttribute('aria-expanded','true');const first=page.locator('.sidebar-nav a').first(),last=page.getByTitle('Log out',{exact:true});await first.focus();await page.keyboard.press('Shift+Tab');await expect(last).toBeFocused();await page.keyboard.press('Tab');await expect(first).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('.sidebar')).not.toHaveClass(/open/);await expect(menu).toBeFocused();await expect(menu).toHaveAttribute('aria-expanded','false');await menu.click();await page.locator('.sidebar-scrim').click({position:{x:(info.project.use.viewport?.width||390)-2,y:50}});await expect(page.locator('.sidebar')).not.toHaveClass(/open/);await expect(menu).toBeFocused()
})
test('WEB-NAV004 closed narrow navigation stays out of keyboard tab order',async({page},info)=>{
 test.skip((info.project.use.viewport?.width||0)>860,'Narrow navigation only');info.annotations.push({type:'control',description:JSON.stringify({id:'web.layout.menu',states:['closed_inert']})});await useFixtureSession(page,'athlete');await page.getByRole('button',{name:'Menu',exact:true}).focus();await page.keyboard.press('Shift+Tab');expect(await page.evaluate(()=>!!document.activeElement?.closest('.sidebar'))).toBe(false)
})
test('WEB-NAV005 responsive drawer returns desktop navigation then safely narrows again',async({page},info)=>{
 test.skip((info.project.use.viewport?.width||0)>860,'Narrow to desktop responsive transition');info.annotations.push({type:'control',description:JSON.stringify({id:'web.layout.menu',states:['responsive_desktop']})});await useFixtureSession(page,'athlete');await page.getByRole('button',{name:'Menu',exact:true}).click();await expect(page.getByRole('dialog',{name:'Navigation'})).toBeVisible();await page.setViewportSize({width:1440,height:900});await expect(page.getByRole('button',{name:'Menu',exact:true})).toBeHidden();await expect(page.getByRole('dialog',{name:'Navigation'})).toHaveCount(0);expect(await page.locator('.sidebar').evaluate(element=>(element as HTMLElement).inert)).toBe(false);await page.locator('.sidebar-nav a[href="/calendar"]').focus();await expect(page.locator('.sidebar-nav a[href="/calendar"]')).toBeFocused();await page.keyboard.press('Enter');await expect(page.locator('.page-title')).toHaveText('Calendar');await page.setViewportSize({width:390,height:844});await expect(page.getByRole('button',{name:'Menu',exact:true})).toBeVisible();expect(await page.locator('.sidebar').evaluate(element=>(element as HTMLElement).inert)).toBe(true)
})
