import {test,expect} from '@playwright/test'
import {useFixtureSession,fixtureApi} from './helpers'
test('WEB-NOTES-DRAFT005 whitespace validation Unicode persistence and failed edit cancellation leave canonical notes truthful',async({page,request},info)=>{
 for(const [id,states]of Object.entries({'web.notes.edit-summary':['whitespace','unicode'],'web.notes.edit-cancel':['draft'],'web.notes.edit-save':['failure'],'web.notes.delete-cancel':['confirm'],'web.notes.filter-all':['populated']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB'),created=await request.post('/api/plan-notes',{...auth,data:{kind:'observation',summary:`Synthetic draft ${Date.now()}`,body:'Original recorded facts',importance:2}});expect(created.status()).toBe(201);const note=await created.json();const canonical=async()=>{const response=await request.get('/api/plan-notes?include_expired=true&limit=200',auth);expect(response.status()).toBe(200);return(await response.json()).find((row:{id:string})=>row.id===note.id)}
 try{await useFixtureSession(page,'athleteB');await page.goto('/notes');await page.getByRole('button',{name:'All',exact:true}).click();const card=page.locator(`[data-note-id="${note.id}"]`);await expect(card).toBeVisible();await card.getByTitle('Edit',{exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit note',exact:true});await dialog.getByLabel('Summary',{exact:true}).fill('   ');await expect(dialog.getByRole('button',{name:'Save',exact:true})).toBeDisabled();await dialog.getByLabel('Summary',{exact:true}).fill('Changed draft 🏃 mémoire');await dialog.getByLabel('Body (optional)',{exact:true}).fill('Uncommitted draft facts');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await canonical()).toEqual(note);await page.reload();await expect(card).toContainText(note.summary)
 await card.getByTitle('Delete',{exact:true}).click();await page.getByRole('dialog',{name:'Delete this note?',exact:true}).getByRole('button',{name:'Cancel',exact:true}).click();expect(await canonical()).toEqual(note);await card.getByTitle('Edit',{exact:true}).click();await dialog.getByLabel('Summary',{exact:true}).fill('Unicode mémoire 跑步 🏃');await dialog.getByLabel('Body (optional)',{exact:true}).fill('Explicit new athlete facts');let failedWrites=0;await page.route(`**/api/plan-notes/${note.id}`,route=>{if(route.request().method()==='PATCH'){failedWrites++;return route.fulfill({status:503,json:{detail:'Synthetic edit outage'}})}return route.continue()});await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Synthetic edit outage');expect(failedWrites).toBe(1);expect(await canonical()).toEqual(note);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.unroute(`**/api/plan-notes/${note.id}`);await card.getByTitle('Edit',{exact:true}).click();await dialog.getByLabel('Summary',{exact:true}).fill('Unicode mémoire 跑步 🏃');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).toHaveCount(0);expect(await canonical()).toMatchObject({id:note.id,summary:'Unicode mémoire 跑步 🏃',body:note.body});await page.reload();await expect(card).toContainText('Unicode mémoire 跑步 🏃')
 }finally{const removed=await request.delete(`/api/plan-notes/${note.id}`,auth);expect(removed.status()).toBe(204)}
})
