import {test,expect}from '@playwright/test'
import {useFixtureSession,fixtureApi,screenshot}from './helpers'
import {randomUUID}from 'node:crypto'

test('WEB-NOTES-001 edit cancel validation identity persistence and failure recovery',async({page,request},info)=>{
 for(const id of ['UI-002','UI-003','UI-004','UI-005','UI-006'])info.annotations.push({type:'scenario',description:id})
 for(const [id,states]of Object.entries({'web.notes.edit-summary':['whitespace','unicode'],'web.notes.edit-kind':['preference'],'web.notes.edit-importance':['3'],'web.notes.edit-expiry':['year-boundary'],'web.notes.edit-cancel':['draft'],'web.notes.edit-save':['valid','reload'],'web.notes.delete-cancel':['confirm'],'web.notes.delete-confirm':['confirm','failure','reload']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB')
 const key=randomUUID().slice(0,8)
 const create=async(summary:string)=>{const res=await request.post('/api/plan-notes',{...auth,data:{kind:'observation',summary,body:'Synthetic original body',importance:2}});expect(res.status()).toBe(201);return await res.json()}
 const first=await create(`Synthetic note A ${key}`)
 const other=await create(`Synthetic note B ${key}`)
 await useFixtureSession(page,'athleteB');await page.goto('/notes')
 const card=page.locator('.note-card').filter({hasText:first.summary})
 const unchanged=async()=>{const res=await request.get('/api/plan-notes',auth);expect(res.ok()).toBeTruthy();const data=await res.json();expect(data.find((n:{id:string})=>n.id===first.id).summary).toBe(first.summary);expect(data.find((n:{id:string})=>n.id===other.id).summary).toBe(other.summary)}
 await card.getByTitle('Edit',{exact:true}).click()
 let dialog=page.getByRole('dialog',{name:'Edit note',exact:true})
 await dialog.getByLabel('Summary',{exact:true}).fill('Unsaved synthetic change')
 await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await unchanged()
 await card.getByTitle('Edit',{exact:true}).click()
 dialog=page.getByRole('dialog',{name:'Edit note',exact:true})
 await dialog.getByLabel('Summary',{exact:true}).fill('   ')
 await expect(dialog.getByRole('button',{name:'Save',exact:true})).toBeDisabled()
 const updated=`Synthetic Unicode café 跑步 ${key}`
 await dialog.getByLabel('Summary',{exact:true}).fill(updated)
 await dialog.getByLabel('Body (optional)',{exact:true}).fill('Synthetic edited body')
 await dialog.getByRole('button',{name:'Preference',exact:true}).click()
 await dialog.getByRole('button',{name:'3',exact:true}).click()
 await dialog.getByLabel('Expires (optional)',{exact:true}).fill('2027-01-01')
 await dialog.getByRole('button',{name:'Save',exact:true}).click()
 await expect(dialog).toHaveCount(0)
 await page.reload()
 const updatedCard=page.locator('.note-card').filter({hasText:updated})
 await expect(updatedCard).toBeVisible()
 const read=await request.get('/api/plan-notes',auth);const data=await read.json();const saved=data.find((n:{id:string})=>n.id===first.id)
 expect(saved).toMatchObject({summary:updated,body:'Synthetic edited body',kind:'preference',importance:3})
 expect(saved.expiresAt).toBe('2027-01-01T13:59:59Z')
 expect(data.find((n:{id:string})=>n.id===other.id).summary).toBe(other.summary)
 await updatedCard.getByTitle('Edit',{exact:true}).click()
 dialog=page.getByRole('dialog',{name:'Edit note',exact:true})
 await expect(dialog.getByLabel('Expires (optional)',{exact:true})).toHaveValue('2027-01-01')
 await dialog.getByRole('button',{name:'Cancel',exact:true}).click()
 await updatedCard.getByTitle('Delete',{exact:true}).click()
 dialog=page.getByRole('dialog',{name:'Delete this note?',exact:true})
 await expect(dialog).toContainText(updated)
 await dialog.getByRole('button',{name:'Cancel',exact:true}).click()
 await expect(updatedCard).toBeVisible()
 const cancelled=await(await request.get('/api/plan-notes',auth)).json();expect(cancelled.find((n:{id:string})=>n.id===first.id).summary).toBe(updated);expect(cancelled.find((n:{id:string})=>n.id===other.id).summary).toBe(other.summary)
 await updatedCard.getByTitle('Delete',{exact:true}).click()
 await page.route(`**/api/plan-notes/${first.id}`,route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'Synthetic delete failed'})}))
 await page.getByRole('dialog').getByRole('button',{name:'Delete',exact:true}).click()
 await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Synthetic delete failed')
 await screenshot(page,info.project.name,'notes-delete-failure')
 const failedState=await(await request.get('/api/plan-notes',auth)).json();expect(failedState.find((n:{id:string})=>n.id===first.id).summary).toBe(updated);expect(failedState.find((n:{id:string})=>n.id===other.id).summary).toBe(other.summary)
 await page.unroute(`**/api/plan-notes/${first.id}`)
 await page.getByRole('dialog').getByRole('button',{name:'Delete',exact:true}).click()
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await page.reload();await expect(page.locator('.note-card').filter({hasText:updated})).toHaveCount(0)
 await expect(page.locator('.note-card').filter({hasText:other.summary})).toBeVisible()
 const remaining=await(await request.get('/api/plan-notes',auth)).json();expect(remaining.some((n:{id:string})=>n.id===first.id)).toBeFalsy()
 await request.delete(`/api/plan-notes/${other.id}`,auth)
})
