import {test,expect} from '@playwright/test'
import {useFixtureSession,fixtureApi} from './helpers'
const kinds=[['decision','Decision'],['preference','Preference'],['constraint','Constraint'],['life_context','Context'],['observation','Observation'],['blocker','Blocker'],['feedback','Feedback']]
test('WEB-NOTES-003 every kind filter and editor kind persist with importance and maximum summary',async({page,request},info)=>{
 for(const id of ['UI-003','UI-004','UI-005','UI-015'])info.annotations.push({type:'scenario',description:id})
 for(const [id,states] of Object.entries({'web.notes.filter-kind':kinds.map(([kind])=>kind),'web.notes.edit-kind':['each-kind'],'web.notes.edit-importance':['1','2','3'],'web.notes.edit-summary':['blank','max-280'],'web.notes.edit-body':['empty','unicode'],'web.notes.edit-expiry':['blank'],'web.notes.edit-open':['expired'],'web.notes.edit-save':['valid']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB'),created:{id:string,summary:string}[]=[]
 const rows=async(kind?:string)=>{const r=await request.get(`/api/plan-notes?include_expired=true&limit=200${kind?`&kind=${kind}`:''}`,auth);expect(r.ok()).toBeTruthy();return await r.json()}
 try{for(const [kind,label] of kinds){const result=await request.post('/api/plan-notes',{...auth,data:{kind,summary:`Synthetic kind ${label} ${Date.now()}`,importance:2,...(kind==='decision'?{expiresAt:'2025-12-31T12:00:00Z'}:{})}});expect(result.status()).toBe(201);created.push(await result.json())}
 await useFixtureSession(page,'athleteB');await page.goto('/notes');await expect(page.locator('.note-card').first()).toBeVisible()
 for(const [kind,label] of kinds){await page.getByRole('button',{name:`${label}s`,exact:true}).click();await expect(page.locator('.note-card')).toHaveCount((await rows(kind)).length);await page.getByRole('button',{name:`${label}s`,exact:true}).click();await expect(page.locator('.note-card')).toHaveCount((await rows(kind)).length)}
 await page.getByRole('button',{name:'All',exact:true}).click();const note=created[0];let card=page.locator('.note-card').filter({hasText:note.summary});await expect(card).toHaveClass(/expired/);await card.getByTitle('Edit',{exact:true}).click();const dialog=page.getByRole('dialog',{name:'Edit note',exact:true});await dialog.getByLabel('Summary',{exact:true}).fill('');await expect(dialog.getByRole('button',{name:'Save',exact:true})).toBeDisabled();const summary='é'.repeat(280);await dialog.getByLabel('Summary',{exact:true}).fill(summary+'extra');await expect(dialog.getByLabel('Summary',{exact:true})).toHaveValue(summary);await dialog.getByLabel('Summary',{exact:true}).fill(summary);await dialog.getByLabel('Body (optional)',{exact:true}).fill('Unicode mémoire 跑步');await dialog.getByLabel('Expires (optional)',{exact:true}).fill('')
 for(let i=0;i<kinds.length;i++){const [kind,label]=kinds[i];if(i>0){card=page.locator('.note-card').filter({hasText:summary});await card.getByTitle('Edit',{exact:true}).click()}await dialog.getByRole('button',{name:label,exact:true}).click();const importance=i%3+1;await dialog.getByRole('button',{name:String(importance),exact:true}).click();await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).toHaveCount(0);const saved=(await rows()).find((r:{id:string})=>r.id===note.id);expect(saved).toMatchObject({kind,importance,summary,body:'Unicode mémoire 跑步',expiresAt:null});await page.reload()}
 card=page.locator('.note-card').filter({hasText:summary});await card.getByTitle('Edit',{exact:true}).click();await dialog.getByLabel('Body (optional)',{exact:true}).fill('');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog).toHaveCount(0);expect((await rows()).find((r:{id:string})=>r.id===note.id).body).toBeNull()
 }finally{for(const note of created)await request.delete(`/api/plan-notes/${note.id}`,auth)}
})
test('WEB-NOTES-004 pending deletion disables cancel and dismissal until server outcome',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-005'})
 for(const [id,states] of Object.entries({'web.notes.delete-confirm':['inflight'],'web.modal.escape-dismiss':['busy'],'web.modal.outside-dismiss':['busy']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB');const r=await request.post('/api/plan-notes',{...auth,data:{kind:'observation',summary:`Synthetic pending ${Date.now()}`,importance:1}});expect(r.status()).toBe(201);const note=await r.json();let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve)
 try{await useFixtureSession(page,'athleteB');await page.goto('/notes');await page.locator('.note-card').filter({hasText:note.summary}).getByTitle('Delete',{exact:true}).click();await page.route(`**/api/plan-notes/${note.id}`,async route=>{await gate;await route.continue()});const dialog=page.getByRole('dialog');await dialog.getByRole('button',{name:'Delete',exact:true}).click();await expect(dialog.getByRole('button',{name:'Working…',exact:true})).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();await page.locator('.modal-overlay').click({position:{x:2,y:2}});await expect(dialog).toBeVisible();await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();release();await expect(dialog).toHaveCount(0)}finally{release();await request.delete(`/api/plan-notes/${note.id}`,auth)}
})
