import {test,expect} from '@playwright/test'
import {useFixtureSession,fixtureApi,screenshot} from './helpers'
test('WEB-PLANS-001 each retained status card opens exact plan and reloads',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-002'},{type:'scenario',description:'UI-015'},{type:'control',description:JSON.stringify({id:'web.plans.card',states:['active','draft','completed','archived']})})
 const auth=fixtureApi('athleteB'),created:{id:string,name:string,status:string}[]=[]
 try{for(const status of ['active','draft','completed','archived']){const r=await request.post('/api/plans',{...auth,data:{name:`Synthetic ${status} plan ${Date.now()}`,activityType:'flexibility',status,startDate:'2026-01-01',endDate:'2026-01-28'}});expect(r.status()).toBe(201);created.push(await r.json())}await useFixtureSession(page,'athleteB')
 for(const plan of created){await page.goto('/plans');const card=page.locator(`[data-plan-id="${plan.id}"]`);await expect(card).toBeVisible();await expect(card.locator('.status-pill')).toHaveText(plan.status);await card.focus();await page.keyboard.press('Enter');await expect(page).toHaveURL(new RegExp(`/plans/${plan.id}$`));await expect(page.locator('.page-title')).toHaveText(plan.name);await page.reload();await expect(page.locator('.page-title')).toHaveText(plan.name)}
 }finally{for(const plan of created)await request.delete(`/api/plans/${plan.id}`,auth)}
})
test('WEB-PLANS-002 completion rating cancel failure retry and exact persisted feedback',async({page,request},info)=>{
 for(const id of ['UI-003','UI-004','UI-005'])info.annotations.push({type:'scenario',description:id})
 for(const [id,states] of Object.entries({'web.celebration.open':['finishable'],'web.celebration.rating':['unset','1','2','3','4','5','toggle-off'],'web.celebration.feedback':['empty','unicode'],'web.celebration.cancel':['draft'],'web.celebration.complete':['finishable','failure'],'web.celebration.done':['success']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB'),name=`Synthetic completion ${Date.now()}`;const r=await request.post('/api/plans',{...auth,data:{name,activityType:'flexibility',status:'active',startDate:'2026-01-01',endDate:'2026-01-28'}});expect(r.status()).toBe(201);const plan=await r.json();const get=async()=>await(await request.get(`/api/plans/${plan.id}`,auth)).json()
 try{expect((await get()).finishable).toBeTruthy();await useFixtureSession(page,'athleteB');await page.goto(`/plans/${plan.id}`);await page.getByRole('button',{name:'Celebrate & wrap up',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Complete plan',exact:true});await expect(dialog.locator('.rating-row button.on')).toHaveCount(0);await expect(dialog.getByLabel('Plan feedback',{exact:true})).toHaveValue('');for(let rating=1;rating<=5;rating++){await dialog.getByRole('button',{name:`${rating} of 5`,exact:true}).click();await expect(dialog.locator('.rating-row button.on')).toHaveCount(rating)}await dialog.getByRole('button',{name:'5 of 5',exact:true}).click();await expect(dialog.locator('.rating-row button.on')).toHaveCount(0);await dialog.getByLabel('Plan feedback',{exact:true}).fill('Unsaved draft');await dialog.getByRole('button',{name:'Not now',exact:true}).click();expect((await get()).status).toBe('active');expect((await get()).metadata.feedback).toBeUndefined()
 await page.getByRole('button',{name:'Celebrate & wrap up',exact:true}).click();await expect(dialog.getByLabel('Plan feedback',{exact:true})).toHaveValue('');await dialog.getByRole('button',{name:'4 of 5',exact:true}).click();const feedback='Synthetic café 跑步 completed feedback';await dialog.getByLabel('Plan feedback',{exact:true}).fill(feedback);await page.route(`**/api/plans/${plan.id}/complete`,route=>route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'Synthetic completion failure'})}));await dialog.getByRole('button',{name:'Complete plan',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Synthetic completion failure');expect((await get()).status).toBe('active');await page.unroute(`**/api/plans/${plan.id}/complete`);await dialog.getByRole('button',{name:'Complete plan',exact:true}).click();await expect(dialog.getByRole('button',{name:'Done',exact:true})).toBeVisible();const saved=await get();expect(saved.status).toBe('completed');expect(saved.metadata).toMatchObject({completion:{rating:4,feedback}});await screenshot(page,info.project.name,'plan-completion-success');await dialog.getByRole('button',{name:'Done',exact:true}).click();await page.reload();expect((await get()).status).toBe('completed');await expect(page.getByRole('button',{name:'Celebrate & wrap up',exact:true})).toHaveCount(0)
 }finally{await request.delete(`/api/plans/${plan.id}`,auth)}
})
