import {test,expect} from '@playwright/test'
import {provisionOwnedActor} from './owned-actor'
test('WEB-COACH-PROFILE-DAYS001 actual profile accepts cleared six and seven availability without weakening initial preview limit',async({page,request},info)=>{
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.coach.availability',states:['unselected','six_days_rejected']})},{type:'evidence-layer',description:'actual owned profile API; 0..7 saves contrasted with initial preview1..5; no program requested'})
 const owned=await provisionOwnedActor(request,page,'Synthetic availability QA'),days=['mon','tue','wed','thu','fri','sat','sun'],facts={goal:{type:'general_fitness'},available_days:['mon','wed','sat'],timezone:'Australia/Brisbane',restrictions:['Explicit synthetic scheduling fact'],benchmark:{level:'established',pace_seconds_per_km:360,weekly_distance_meters:18000,long_run_meters:7000,source:'Synthetic athlete supplied availability facts',observed_at:new Date().toISOString()}},read=async()=>{const response=await request.get('/api/coaching/profile',owned.auth);expect(response.status()).toBe(200);return await response.json()}
 try{for(const count of [0,6,7]){const accepted=await request.put('/api/coaching/profile',{...owned.auth,data:{...facts,available_days:days.slice(0,count)}});expect(accepted.status()).toBe(200);expect((await read()).available_days).toEqual(days.slice(0,count))}expect((await request.put('/api/coaching/profile',{...owned.auth,data:facts})).status()).toBe(200);let previews=0;page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/coaching/program')previews++});await page.goto('/coach');await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(facts.benchmark.source)
 for(const count of [0,6,7]){for(const day of days){const button=page.getByRole('button',{name:day,exact:true});if(await button.getAttribute('aria-pressed')==='true')await button.click()}for(const day of days.slice(0,count))await page.getByRole('button',{name:day,exact:true}).click();await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'Coaching profile saved.'})).toBeVisible();expect((await read()).available_days).toEqual(days.slice(0,count));expect((await read()).restrictions).toEqual(facts.restrictions);await page.reload();await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(facts.benchmark.source);for(const day of days)await expect(page.getByRole('button',{name:day,exact:true})).toHaveAttribute('aria-pressed',String(days.slice(0,count).includes(day)));await page.getByRole('button',{name:'Preview program',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Choose one to five training days.');expect(previews).toBe(0)}
 }finally{await owned.cleanup()}
})
