import {test,expect} from '@playwright/test'
import {provisionOwnedActor} from './owned-actor'
test('WEB-COACH-PRECISION001 availability-only and source-only save preserve untouched benchmark truth through reload',async({page,request},info)=>{
 info.annotations.push({type:'evidence-layer',description:'actual owned profile public API; exact canonical timestamp and fractional pace; no program preview'})
 await new Promise(resolve=>setTimeout(resolve,13000));const owned=await provisionOwnedActor(request,page,'Synthetic precision QA')
 const supplied={goal:{type:'general_fitness'},available_days:['mon'],timezone:'Australia/Brisbane',restrictions:['Synthetic current restriction'],benchmark:{level:'established',pace_seconds_per_km:360.375,weekly_distance_meters:18000.125,long_run_meters:7000.375,source:'Synthetic explicit precision facts',observed_at:new Date(Date.now()-60000).toISOString().replace(/\.\d{3}Z$/,'.789Z'),confidence:0.85}}
 const read=async()=>{const response=await request.get('/api/coaching/profile',owned.auth);expect(response.status()).toBe(200);return await response.json()}
 try{const seeded=await request.put('/api/coaching/profile',{...owned.auth,data:supplied});expect(seeded.status()).toBe(200);const canonical=await read();expect(canonical.benchmark.pace_seconds_per_km).toBe(360.375);expect(Date.parse(canonical.benchmark.observed_at)).toBe(Date.parse(supplied.benchmark.observed_at));await page.goto('/coach');await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(supplied.benchmark.source);await page.getByRole('button',{name:'tue',exact:true}).click();await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect((await read()).benchmark).toEqual(canonical.benchmark);await page.reload();await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue(supplied.benchmark.source);await page.getByLabel('Benchmark source',{exact:true}).fill('Synthetic changed provenance');await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');expect((await read()).benchmark).toEqual({...canonical.benchmark,source:'Synthetic changed provenance'});await page.reload();await expect(page.getByLabel('Benchmark source',{exact:true})).toHaveValue('Synthetic changed provenance');expect((await read()).benchmark.pace_seconds_per_km).toBe(360.375);expect((await read()).benchmark.observed_at).toBe(canonical.benchmark.observed_at);await page.getByLabel('Benchmark confidence (optional, 0–1)',{exact:true}).fill('');const saving=page.waitForRequest(r=>r.method()==='PUT'&&new URL(r.url()).pathname==='/api/coaching/profile');await page.getByRole('button',{name:'Save coaching profile',exact:true}).click();expect((await saving).postDataJSON().benchmark).not.toHaveProperty('confidence');await expect(page.getByRole('status')).toHaveText('Coaching profile saved.');const cleared=await read();expect(cleared.benchmark.confidence).toBeNull();expect(cleared.benchmark.pace_seconds_per_km).toBe(360.375);expect(cleared.benchmark.observed_at).toBe(canonical.benchmark.observed_at);await page.reload();await expect(page.getByLabel('Benchmark confidence (optional, 0–1)',{exact:true})).toHaveValue('')
 }finally{await owned.cleanup()}
})
