import {test,expect} from '@playwright/test'
import {readFileSync} from 'node:fs'
import path from 'node:path'
import {screenshot,expectNoOverflow} from './helpers'
test('WEB-COACH011 actual stored proposal exposes bounded evidence and closes without prescription writes',async({page,request},info)=>{
 const account=JSON.parse(readFileSync(path.resolve('../../../artifacts/baseline-server/isolated-verification/web-evidence.private.json'),'utf8'))
 const login=await request.post('/api/auth/login',{data:{...account,deviceName:'Synthetic evidence display QA'}});expect(login.status()).toBe(200);const session=await login.json();await page.addInitScript(({token,tokenId,user})=>{localStorage.setItem('loopback.token',token);localStorage.setItem('loopback.tokenId',tokenId);localStorage.setItem('loopback.user',JSON.stringify(user))},session)
 const headers={Authorization:`Bearer ${session.token}`};const status=await request.get('/api/coaching/status',{headers});expect(status.status()).toBe(200);const proposal=(await status.json()).proposals.find((row:any)=>row.id==='02efff8c-bac3-4d5e-b890-a743cff9bfcb');expect(proposal.status).toBe('awaiting_approval');const planBefore=await (await request.get(`/api/plans/${proposal.plan_id}`,{headers})).json();const queueBefore=await (await request.get('/api/queue',{headers})).json();let writes=0;page.on('request',req=>{if(/\/api\/coaching\/proposals\/.*\/(accept|dismiss)$/.test(req.url()))writes++})
 info.annotations.push({type:'control',description:JSON.stringify({id:'web.coach.proposal-review',states:['awaiting_approval','correct_identity']})},{type:'control',description:JSON.stringify({id:'web.coach.proposal-close',states:['no_activation']})})
 await page.goto('/coach');await page.getByTestId(`coaching-proposal-${proposal.id}`).getByRole('button',{name:'Review proposal',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Review coaching proposal',exact:true}),evidence=dialog.getByRole('region',{name:'Training evidence'});await expect(dialog).toBeFocused();await expect(evidence).toContainText('Ingestion completeness: unknown');await expect(evidence).toContainText(`Recorded totals: ${proposal.metrics.session_count} sessions`);await expect(evidence).toContainText(`${proposal.evidenceSummary.independentEligibleDays} independent eligible days`);await expect(evidence).toContainText('Gap coverage: unknown');await expect(evidence).toContainText('Explicit missed sessions:');await expect(dialog.getByRole('button',{name:'Approve changes',exact:true})).toBeEnabled();await expectNoOverflow(page);await screenshot(page,info.project.name,'proposal-evidence-top-current');await dialog.getByRole('button',{name:'Close without changes',exact:true}).scrollIntoViewIfNeeded();await screenshot(page,info.project.name,'proposal-evidence-actions-current');await dialog.getByRole('button',{name:'Close without changes',exact:true}).click();expect(writes).toBe(0);await page.reload();const planAfter=await(await request.get(`/api/plans/${proposal.plan_id}`,{headers})).json(),queueAfter=await(await request.get('/api/queue',{headers})).json();expect(planAfter).toEqual(planBefore);expect(queueAfter).toEqual(queueBefore);const after=(await(await request.get('/api/coaching/status',{headers})).json()).proposals.find((row:any)=>row.id===proposal.id);expect(after.status).toBe('awaiting_approval')
})
