import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {useFixtureSession,fixtureApi,expectNoOverflow,screenshot} from './helpers'
async function create(request:any,auth:any,title:string){const r=await request.post('/api/queue',{...auth,data:{activityType:'running',title}});expect(r.status()).toBe(201);return await r.json()}
test('WEB-QUEUE-001 pending fetched synced delete cancel failure inflight and correct persistent row',async({page,request},info)=>{
 for(const id of ['UI-002','UI-003','UI-004','UI-005'])info.annotations.push({type:'scenario',description:id})
 for(const [id,states] of Object.entries({'web.queue.delete-open':['pending','fetched','synced'],'web.queue.delete-cancel':['confirm'],'web.queue.delete-confirm':['confirm','inflight','failure']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB'),created:string[]=[];const rows=async()=>{const r=await request.get('/api/queue',auth);expect(r.ok()).toBeTruthy();return await r.json()}
 try{const other=await create(request,auth,`Synthetic retained queue ${Date.now()}`);created.push(other.id);await useFixtureSession(page,'athleteB')
 for(const status of ['pending','fetched','synced']){const item=await create(request,auth,`Synthetic ${status} queue ${Date.now()}`);created.push(item.id);if(status!=='pending')expect((await request.patch(`/api/queue/${item.id}/status`,{...auth,data:{status}})).ok()).toBeTruthy();await page.goto('/queue');const card=page.locator('.queue-card').filter({hasText:item.title});await expect(card).toBeVisible();await expect(card.locator('.status-pill')).toContainText(status);await card.getByTitle('Delete queue item',{exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect((await rows()).some((r:{id:string})=>r.id===item.id)).toBeTruthy();await card.getByTitle('Delete queue item',{exact:true}).click()
 await page.route(`**/api/queue/${item.id}`,route=>route.request().method()==='DELETE'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'Synthetic queue delete failure'})}):route.continue());await page.getByRole('dialog').getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Synthetic queue delete failure');expect((await rows()).some((r:{id:string})=>r.id===item.id)).toBeTruthy();await page.unroute(`**/api/queue/${item.id}`)
 let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route(`**/api/queue/${item.id}`,async route=>{await gate;await route.continue()});await page.getByRole('dialog').getByRole('button',{name:'Delete',exact:true}).click();await expect(page.getByRole('button',{name:'Working…',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();release();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(card).toHaveCount(0);expect((await rows()).some((r:{id:string})=>r.id===item.id)).toBeFalsy();expect((await rows()).some((r:{id:string})=>r.id===other.id)).toBeTruthy();await page.unroute(`**/api/queue/${item.id}`)}
 }finally{for(const id of created)await request.delete(`/api/queue/${id}`,auth)}
})
test('WEB-QUEUE-002 feedback acknowledgement failure is truthful and retry persists once',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-003'},{type:'scenario',description:'UI-007'},{type:'control',description:JSON.stringify({id:'web.queue.feedback-ack',states:['unacknowledged','failure','inflight']})})
 const auth=fixtureApi('athleteB'),title=`Synthetic feedback ${Date.now()}`,item=await create(request,auth,title),id=randomUUID(),now=new Date().toISOString();const r=await request.post('/api/workouts/feedback',{...auth,data:{id,workoutId:item.id,workoutName:title,scheduledDate:now,detectedAt:now,reason:'busy',reasonNote:'Synthetic fixture response',action:'adjust',dismissed:false}});expect(r.status()).toBe(201)
 try{await useFixtureSession(page,'athleteB');await page.goto('/queue');const card=page.locator('.fb-card').filter({hasText:title});await expect(card).toBeVisible();await page.route('**/api/workouts/feedback',route=>route.request().method()==='POST'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'Synthetic acknowledgement failure'})}):route.continue());await card.getByRole('button',{name:'Acknowledge',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Synthetic acknowledgement failure');await page.unroute('**/api/workouts/feedback');const before=await request.get('/api/workouts/feedback?limit=100',auth);expect((await before.json()).find((f:{id:string})=>f.id===id).acknowledgedAt).toBeNull()
 let release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);await page.route('**/api/workouts/feedback',async route=>{if(route.request().method()==='POST')await gate;await route.continue()});await card.getByRole('button',{name:'Acknowledge',exact:true}).click();await expect(card.getByRole('button',{name:'Saving…',exact:true})).toBeDisabled();release();await expect(card.getByText('Acknowledged',{exact:true})).toBeVisible();await page.reload();await expect(card.getByText('Acknowledged',{exact:true})).toBeVisible();const after=await request.get('/api/workouts/feedback?limit=100',auth);const rows=await after.json();expect(rows.filter((f:{id:string})=>f.id===id)).toHaveLength(1);expect(rows.find((f:{id:string})=>f.id===id).acknowledgedAt).toBeTruthy()
 }finally{await request.delete(`/api/queue/${item.id}`,auth)}
})
test('WEB-QUEUE-003 delete icon meets selected contrast and target-size criteria',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-011'},{type:'control',description:JSON.stringify({id:'web.queue.delete-open',states:['contrast','minimum_target_size']})})
 const auth=fixtureApi('athleteB'),item=await create(request,auth,`Synthetic queue contrast ${randomUUID()}`)
 try{await useFixtureSession(page,'athleteB');await page.goto('/queue');const card=page.locator(`[data-queue-id="${item.id}"]`),button=card.getByTitle('Delete queue item',{exact:true});await expect(button).toBeVisible();const colors=await button.evaluate(el=>({foreground:getComputedStyle(el).color,background:getComputedStyle(el.closest('.queue-card')!).backgroundColor}));const luminance=(color:string)=>{const values=color.match(/[\d.]+/g)!.slice(0,3).map(Number).map(v=>{v/=255;return v<=0.04045?v/12.92:((v+0.055)/1.055)**2.4});return values[0]*0.2126+values[1]*0.7152+values[2]*0.0722};const a=luminance(colors.foreground),b=luminance(colors.background),ratio=(Math.max(a,b)+0.05)/(Math.min(a,b)+0.05);expect(ratio,JSON.stringify(colors)).toBeGreaterThanOrEqual(3);const bounds=await button.boundingBox();expect(bounds?.width).toBeGreaterThanOrEqual(44);expect(bounds?.height).toBeGreaterThanOrEqual(44);expect(bounds!.x).toBeGreaterThanOrEqual(0);expect(bounds!.x+bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);await expectNoOverflow(page);await card.scrollIntoViewIfNeeded();await screenshot(page,info.project.name,'queue-readable-delete-control')
 }finally{await request.delete(`/api/queue/${item.id}`,auth)}
})
