import {test,expect} from '@playwright/test'
import {useFixtureSession,fixtureApi} from './helpers'
test('WEB-SETTINGS-001 clipboard rejection cannot claim copied and leaves token revocable',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'UI-012'},{type:'control',description:JSON.stringify({id:'web.settings.token-copy',states:['created','clipboard-failure']})})
 await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(new Error('Clipboard denied by test'))},configurable:true}))
 await useFixtureSession(page,'athleteB');await page.goto('/settings');await page.getByRole('button',{name:'New token',exact:true}).click();await expect(page.getByRole('dialog',{name:'Create token',exact:true})).toBeVisible();await page.getByLabel('Token name',{exact:true}).fill(`Synthetic clipboard ${Date.now()}`)
 const response=page.waitForResponse(r=>r.url().endsWith('/api/auth/tokens')&&r.request().method()==='POST');await page.getByRole('button',{name:'Create token',exact:true}).click();const result=await response;expect(result.ok()).toBeTruthy();const minted=await result.json()
 try{await page.getByRole('button',{name:'Copy token',exact:true}).click();await expect(page.getByRole('button',{name:'Copied',exact:true})).toHaveCount(0);await expect(page.getByRole('alert')).toContainText('Could not copy')}
 finally{const cleanup=await request.delete(`/api/auth/tokens/${minted.tokenId}`,fixtureApi('athleteB'));expect(cleanup.ok()).toBeTruthy()}
})
test('WEB-SETTINGS-002 token cancel invalid failure retry expiry reload revoke cancel and revoke persist',async({page,request},info)=>{
 info.annotations.push({type:'scenario',description:'AUTH-007'},{type:'scenario',description:'UI-003'},{type:'scenario',description:'UI-004'})
 for(const [id,states] of Object.entries({'web.settings.token-open':['default'],'web.settings.token-name':['whitespace','unicode'],'web.settings.token-cancel':['draft'],'web.settings.token-create':['valid','failure'],'web.settings.token-expiry':['never','30-days','90-days','1-year'],'web.settings.token-done':['created'],'web.settings.token-revoke-open':['other'],'web.settings.token-revoke-cancel':['confirm'],'web.settings.token-revoke-confirm':['other']}))info.annotations.push({type:'control',description:JSON.stringify({id,states})})
 const auth=fixtureApi('athleteB');const tokens=async()=>{const r=await request.get('/api/auth/me',auth);expect(r.ok()).toBeTruthy();return (await r.json()).tokens}
 // Retire only this task's synthetic token left by the earlier cleanup-harness defect.
 for(const token of await tokens())if(token.name.startsWith('Synthetic clipboard '))expect((await request.delete(`/api/auth/tokens/${token.id}`,auth)).ok()).toBeTruthy()
 const before=await tokens();await useFixtureSession(page,'athleteB');await page.goto('/settings');await page.getByRole('button',{name:'New token',exact:true}).click();await expect(page.getByRole('dialog',{name:'Create token',exact:true})).toBeVisible();await page.getByLabel('Token name',{exact:true}).fill('   ');await expect(page.getByRole('button',{name:'Create token',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect((await tokens()).map((t:{id:string})=>t.id)).toEqual(before.map((t:{id:string})=>t.id))
 for(const [choice,days] of [['Never',null],['30 days',30],['90 days',90],['1 year',365]] as const){await page.getByRole('button',{name:'New token',exact:true}).click();const name=`Synthetic expiry ✓ ${choice} ${Date.now()}`;await page.getByLabel('Token name',{exact:true}).fill(name);await page.getByRole('button',{name:choice,exact:true}).click()
 if(choice==='Never'){await page.route('**/api/auth/tokens',async route=>route.request().method()==='POST'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({detail:'Synthetic mint failure'})}):route.continue());await page.getByRole('button',{name:'Create token',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Synthetic mint failure');expect((await tokens()).some((t:{name:string})=>t.name===name)).toBeFalsy();await page.unroute('**/api/auth/tokens')}
 await page.getByRole('button',{name:'Create token',exact:true}).click();await expect(page.getByText('Token created',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Done',exact:true}).click();await page.reload();const row=page.locator('.token-row').filter({hasText:name});await expect(row).toBeVisible();const created=(await tokens()).find((t:{name:string})=>t.name===name);expect(created).toBeTruthy();if(days===null)expect(created.expiresAt).toBeNull();else expect(Math.abs(new Date(created.expiresAt).getTime()-Date.now()-days*86400000)).toBeLessThan(20000)
 await row.getByRole('button',{name:'Revoke',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect((await tokens()).some((t:{id:string})=>t.id===created.id)).toBeTruthy();await row.getByRole('button',{name:'Revoke',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Revoke',exact:true}).click();await expect(row).toHaveCount(0);expect((await tokens()).some((t:{id:string})=>t.id===created.id)).toBeFalsy()}
})
