import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {useFixtureSession,fixtureApi} from './helpers'
test('WEB-WORKOUT-CHART001 persisted heart rate and cadence points retain canonical values and all keyboard pointer touch dismissal states',async({page,request},info)=>{
 const auth=fixtureApi('athleteB'),ids=[randomUUID(),randomUUID()],start=Date.now()-120_000,timestamps=[0,30,60].map(seconds=>new Date(start+seconds*1000).toISOString()),heartRate=[121,143,157].map((value,index)=>({value,timestamp:timestamps[index]})),cadence=[161,172,183].map((value,index)=>({value,timestamp:timestamps[index]}))
 for(const id of ['heart-rate','running-cadence'])info.annotations.push({type:'control',description:JSON.stringify({id:`web.workout-detail.chart-${id}`,states:['first','middle','last','keyboard','focus','escape',info.project.use.hasTouch?'touch':'pointer-leave','missing']})})
 try{for(let i=0;i<ids.length;i++){const response=await request.post('/api/workouts',{...auth,data:{id:ids[i],activityType:'running',startDate:new Date(start).toISOString(),endDate:new Date(start+90_000).toISOString(),duration:90,totalDistance:300,source:'Synthetic chart QA',data:{heartRate:i===0?heartRate:[],cadence:i===0?cadence:[]}}});expect(response.status()).toBe(201)}const canonical=await request.get(`/api/workouts/${ids[0]}/heartrate`,auth);expect(canonical.status()).toBe(200);expect(await canonical.json()).toEqual(heartRate);const recorded=await request.get(`/api/workouts/${ids[0]}`,auth);expect((await recorded.json()).data.cadence).toEqual(cadence)
 await useFixtureSession(page,'athleteB');await page.goto(`/workouts/${ids[0]}`)
 for(const spec of [{name:'Heart rate trace',points:heartRate,unit:'bpm',point:true},{name:'Running cadence',points:cadence,unit:'spm',point:false}]){const chart=page.getByRole('group',{name:spec.name,exact:true});await chart.scrollIntoViewIfNeeded();await chart.focus();await expect(chart).toBeFocused();const tooltip=chart.getByRole('tooltip');for(const index of [0,1,2]){await page.keyboard.press('Home');for(let step=0;step<index;step++)await page.keyboard.press('ArrowRight');await expect(tooltip).toContainText(`${spec.points[index].value} ${spec.unit}`);await expect(tooltip).toContainText(['0:00 in','0:30 in','1:00 in'][index])}await page.keyboard.press('Escape');await expect(tooltip).toHaveCount(0);const box=await chart.boundingBox();expect(box).not.toBeNull();const x=box!.x+box!.width*.5,y=box!.y+box!.height*.5;if(info.project.use.hasTouch)await page.touchscreen.tap(x,y);else await page.mouse.move(x,y);await expect(tooltip).toContainText(`${spec.points[1].value} ${spec.unit}`);if(info.project.use.hasTouch){await chart.focus();await page.keyboard.press('Escape')}else await page.mouse.move(0,0);await expect(tooltip).toHaveCount(0)}await page.reload();await expect(page.getByRole('group',{name:'Heart rate trace',exact:true})).toBeVisible();await page.goto(`/workouts/${ids[1]}`);await expect(page.getByRole('button',{name:'Raw metadata JSON',exact:true})).toBeVisible();await expect(page.getByRole('group',{name:'Heart rate trace',exact:true})).toHaveCount(0);await expect(page.getByRole('group',{name:'Running cadence',exact:true})).toHaveCount(0);const empty=await request.get(`/api/workouts/${ids[1]}/heartrate`,auth);expect(await empty.json()).toEqual([])
 }finally{for(const id of ids){const removed=await request.delete(`/api/workouts/${id}`,auth);expect([204,404]).toContain(removed.status())}}
})
