import {test,expect} from '@playwright/test'
import {randomUUID} from 'node:crypto'
import {useFixtureSession,fixtureApi} from './helpers'
test('WEB-WORKOUT-MAP001 canonical route remains visible when external tiles fail and pan zoom reload cannot rewrite recorded GPS',async({page,request},info)=>{
 info.annotations.push({type:'evidence-layer',description:'real synthetic GPS API with external CARTO tile requests deliberately aborted'},{type:'control',description:JSON.stringify({id:'web.workout-detail.route-map',states:['populated','keyboard-pan','pointer-pan','double-click-zoom','reload-restores-recorded-route','external-tiles-failure','missing']})},{type:'control',description:JSON.stringify({id:'web.workout-detail.map-attribution',states:['conditional-map','external-link']})})
 const auth=fixtureApi('athleteB'),ids=[randomUUID(),randomUUID()],route=[{latitude:-27.47,longitude:153.02},{latitude:-27.472,longitude:153.023},{latitude:-27.475,longitude:153.026}],now=Date.now();let tileFailures=0
 await page.route('https://*.basemaps.cartocdn.com/**',route=>{tileFailures++;return route.abort('failed')})
 try{for(let i=0;i<ids.length;i++){const created=await request.post('/api/workouts',{...auth,data:{id:ids[i],activityType:'running',startDate:new Date(now-120_000).toISOString(),endDate:new Date(now-30_000).toISOString(),duration:90,totalDistance:800,source:'Synthetic GPS QA',data:{route:i===0?route:[]}}});expect(created.status()).toBe(201)}const read=async()=>{const response=await request.get(`/api/workouts/${ids[0]}`,auth);expect(response.status()).toBe(200);return(await response.json()).data.route};expect(await read()).toEqual(route);await useFixtureSession(page,'athleteB');await page.goto(`/workouts/${ids[0]}`);const map=page.locator('.leaflet-container');await expect(map).toBeVisible();await map.scrollIntoViewIfNeeded();await expect.poll(()=>tileFailures).toBeGreaterThan(0);await expect(map.locator('path.leaflet-interactive')).toHaveCount(3);const pane=map.locator('.leaflet-map-pane'),initial=await pane.getAttribute('style');await map.focus();await expect(map).toBeFocused();await page.keyboard.press('ArrowRight');await expect(pane).not.toHaveAttribute('style',initial||'');const keyboard=await pane.getAttribute('style'),box=await map.boundingBox();expect(box).not.toBeNull();await page.mouse.move(box!.x+box!.width*.5,box!.y+box!.height*.5);await page.mouse.down();await page.mouse.move(box!.x+box!.width*.65,box!.y+box!.height*.55,{steps:8});await page.mouse.up();await expect(pane).not.toHaveAttribute('style',keyboard||'');const tiles=map.locator('.leaflet-tile-container').last(),zoomBefore=await tiles.getAttribute('style');await map.dblclick({position:{x:box!.width*.5,y:box!.height*.5}});await expect.poll(async()=>map.locator('.leaflet-tile-container').last().getAttribute('style')).not.toBe(zoomBefore);const attribution=map.locator('.leaflet-control-attribution');await expect(attribution).toContainText('OpenStreetMap');await expect(attribution).toContainText('CARTO');await expect(attribution.getByRole('link',{name:'Leaflet',exact:true})).toHaveAttribute('href',/leafletjs.com/);expect(await read()).toEqual(route);await page.reload();await expect(map).toBeVisible();await expect(map.locator('path.leaflet-interactive')).toHaveCount(3);expect(await read()).toEqual(route);await page.goto(`/workouts/${ids[1]}`);await expect(page.getByRole('button',{name:'Raw metadata JSON',exact:true})).toBeVisible();await expect(page.locator('.leaflet-container')).toHaveCount(0);await expect(page.locator('.leaflet-control-attribution')).toHaveCount(0)
 }finally{for(const id of ids){const removed=await request.delete(`/api/workouts/${id}`,auth);expect([204,404]).toContain(removed.status())}}
})
